Repository dosbox-staging/dosbox-staging, pull requests merged in 2019-12, with the labels that each got.

#76 Use python explicitly in pwsh
  .github/workflows/windows.yml
Labels: bug

#80 Switch from std::vector to std::array
  include/bios_disk.h
  src/ints/bios_disk.cpp
Labels: cleanup

#58 Remove code ifdefed for OS/2
  README
  configure.ac
  include/cross.h
  src/dos/Makefile.am
  src/dos/cdrom.cpp
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
  src/dos/cdrom_ioctl_os2.cpp
  src/dos/dos_mscdex.cpp
  src/dos/dos_programs.cpp
  src/dos/drive_cache.cpp
  src/dos/drive_overlay.cpp
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
  src/hardware/serialport/libserial.cpp
  src/hardware/serialport/misc_util.cpp
  src/hardware/serialport/misc_util.h
  src/misc/cross.cpp
  src/shell/shell.cpp
Labels: cleanup

#85 Stop submitting builds to Coverity for now
  .github/workflows/dormant/coverity.yml
Labels: bug

#89 Add new features to warning counter script
  scripts/count-warnings.py
Labels: enhancement

#91 Avoid libpng 1.2 dependency for Ubuntu releases
  .github/workflows/linux.yml
Labels: bug

#93 Fix --enabled-debug on Windows MSYS2
  .github/scripts/shrink-msys2.sh
  .github/workflows/config.yml
  INSTALL
  configure.ac
Labels: bug

#98 Adjust time at which "Config heavy" workflow runs
  .github/workflows/config.yml
Labels: bug

#103 Improve 'pause' and 'dir' commands
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: bug
