Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-11, with the labels that each got.

#694 Fix CPUID for emulated Pentium and 486
  src/cpu/cpu.cpp
Labels: bug

#702 Include FluidSynth's dependencies when using the static library
  contrib/static-fluidsynth/Makefile
Labels: Raspberry Pi, bug

#700 Add libpng-dev to the list of dependencies when using an APT repo
  scripts/automator/packages/manager-apt
Labels: bug

#701 Avoid resampling FluidSynth by using the mixer's negotiated rate
  src/midi/midi_fluidsynth.cpp
Labels: enhancement

#699 Scale soundfont levels by an optional percentage
  src/midi/midi_fluidsynth.cpp
Labels: enhancement

#706 Correct spelling mistakes
  .github/scripts/build-autofdo.sh
  .github/scripts/fetch-and-merge-afdo.sh
  .github/scripts/fetch-and-merge-profraw.sh
  .github/scripts/shrink-brew.sh
  .github/scripts/shrink-msys2.sh
  .github/workflows/coverity.md
  docs/README.video
  include/bios.h
  include/byteorder.h
  include/dos_inc.h
  include/mem.h
  include/mem_host.h
  include/mem_unaligned.h
  include/mixer.h
  include/regs.h
  include/setup.h
  include/soft_limiter.h
  include/support.h
  include/timer.h
  scripts/automator/build/gcc-haiku_x86_64
  scripts/automator/build/gcc-linux_x86_64
  scripts/automator/build/gcc-msys_nt_x86_64
  scripts/automator/main.sh
  scripts/list-build-dependencies.sh
Labels: cleanup

#711 Create program stub for LS command
  .github/workflows/windows.yml
  src/dos/Makefile.am
  src/dos/dos_programs.cpp
  src/dos/program_ls.cpp
  src/dos/program_ls.h
  src/shell/shell_cmds.cpp
  vs/dosbox.vcxproj
Labels: bug

#713 Rename pc_zero_offset to zero_offset
  src/dosbox.cpp
  src/hardware/pcspeaker.cpp
Labels: cleanup

#717 Add an option for unblocking the OS screensaver
  src/gui/sdlmain.cpp
Labels: bug

#722 Skip removal of already absent files
  src/dos/drive_local.cpp
Labels: regression

#726 Specify that -t iso is a synonym for -t cdrom
  src/dos/dos_programs.cpp
Labels: documentation
