Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-08, with the labels that each got.

#528 Fix 'dir /p' cmd in non-standard text modes
  src/shell/shell_cmds.cpp
Labels: bug

#520 Implement OpenGL pixel-perfect mode
  src/gui/sdlmain.cpp
Labels: enhancement

#533 Cleanup presumptive drive_local library calls (Coverity fixes)
  include/dos_system.h
  src/dos/drive_local.cpp
Labels: cleanup

#536 Prevent shell from injecting spurious newlines
  src/misc/programs.cpp
  src/shell/shell.cpp
Labels: bug

#538 Simplify drive_local's delete() function with actionable checks only
  include/drives.h
  src/dos/drive_local.cpp
Labels: cleanup

#547 Force pixel-perfect to respect aspect.ratio setting
  src/gui/render.cpp
Labels: bug

#552 Use the platform-specific fluidsynth package when building under MSYS2
  scripts/automator/packages/manager-msys2
Labels: bug

#557 Don't explicitly disable Microsoft bitfields for autotools builds
  configure.ac
Labels: bug

#560 Add FluidSynth dll to Windows package
  .github/workflows/windows.yml
Labels: bug

#554 Cache vcpkg packages on a weekly basis
  .github/workflows/windows.yml
Labels: CI, enhancement

#576 Update PVS Studio to version 7.09.41189.57
  .github/workflows/pvs-studio.yml
Labels: CI

#580 Fix switch-case typo in GUS and add more debug logging
  src/hardware/gus.cpp
Labels: cleanup

#589 Fix boot failure from Drive C
  src/dos/dos_programs.cpp
Labels: bug
