Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-05, with the labels that each got.

#338 Scan Windows release packages using Microsoft Defender
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: CI, enhancement

#340 Limit string concatenation to the target's length
  src/dos/dos_programs.cpp
  src/dos/drive_iso.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/misc/cross.cpp
  src/shell/shell_misc.cpp
Labels: cleanup

#343 Prevent platform builds failure
  .github/workflows/platforms.yml
Labels: CI, bug

#344 Fix compilation for devkit pro toolchain
  src/hardware/mame/fmopl.cpp
  src/hardware/mame/ymf262.cpp
Labels: bug

#346 Clean code around setting png "Software" keyword
  src/hardware/hardware.cpp
Labels: cleanup

#348 Allow GCC's LTO on all platforms
  scripts/automator/build/gcc-defaults
  scripts/automator/build/gcc-linux_x86_64
Labels: enhancement

#265 Document contributing guidelines
  CONTRIBUTING.md
Labels: discussion, documentation

#356 Fix APT package names and minimum OS ver
  README.md
Labels: documentation

#357 Add Haiku OS support to build system
  configure.ac
  scripts/automator/build/clang-haiku_x86_64
  scripts/automator/build/gcc-haiku_x86_64
  scripts/automator/build/os-haiku
  scripts/automator/packages/clang-haikuports
  scripts/automator/packages/manager-haikuports
  scripts/build.md
Labels: enhancement

#368 Internationalize generic name in desktop file
  contrib/linux/dosbox-staging.desktop
Labels: Linux, enhancement

#367 Use the project's new repo URL
  .clang-format
  BUILD.md
  CONTRIBUTING.md
  scripts/import-from-svn/import-from-svn.sh
Labels: cleanup

#373 Use std::string for name in DOS_File class
  include/dos_system.h
  include/drives.h
  src/dos/dos_devices.cpp
  src/dos/drive_iso.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
Labels: cleanup

#375 Create release packages for ARM and IBM platforms
  .github/workflows/platforms.yml
Labels: CI, enhancement

#398 Cleanup in dyn_fpu header (cleanup before merge r4342)
  src/cpu/core_dyn_x86/dyn_fpu.h
Labels: cleanup

#403 Add support for binding more controller axes
  src/gui/sdl_mapper.cpp
Labels: bug
