Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-03, with the labels that each got.

#191 Use sh-compatible syntax in configure.ac
  configure.ac
Labels: bug

#186 Migrate some members of the Player class to smart pointers
  include/support.h
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: cleanup

#194 fixup! Warning iterator-past-end-of-container
  src/dos/cdrom_image.cpp
Labels: bug

#199 Refresh copyrights and headers
  src/libs/decoders/SDL_sound.c
  src/libs/decoders/SDL_sound.h
  src/libs/decoders/SDL_sound_internal.h
  src/libs/decoders/flac.c
  src/libs/decoders/mp3.cpp
  src/libs/decoders/mp3_seek_table.cpp
  src/libs/decoders/mp3_seek_table.h
  src/libs/decoders/opus.cpp
  src/libs/decoders/vorbis.c
  src/libs/decoders/wav.c
Labels: cleanup, documentation

#202 Ensure the first seek isn't cached
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: bug

#185 Add pixel-perfect scaling feature
  configure.ac
  include/video.h
  src/Makefile.am
  src/gui/render.cpp
  src/gui/sdlmain.cpp
  src/libs/Makefile.am
  src/libs/ppscale/Makefile.am
  src/libs/ppscale/ppscale.c
  src/libs/ppscale/ppscale.h
  vs/dosbox.vcxproj
Labels: enhancement

#203 Prevent env:OPUSFILE_LIBS from enabling Opus
  configure.ac
Labels: bug

#212 Inject newlines before displaying DOS prompt
  include/programs.h
  src/dos/dos_execute.cpp
  src/misc/programs.cpp
  src/shell/shell_misc.cpp
Labels: bug

#218 Add handling for user-defined sets of files
  scripts/dump-preprocessor-defines.sh
  scripts/verify-ctype-algorithm-include-order.sh
Labels: cleanup

#235 Use ccache if available
  scripts/automator/build/clang-defaults
  scripts/automator/build/compiler-defaults
  scripts/automator/build/gcc-defaults
  scripts/automator/build/os-defaults
Labels: enhancement

#237 Turn on CI jobs for pull_request event
  .github/workflows/analysis.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: CI, enhancement

#236 Cache ccache across CI workflows
  .github/workflows/analysis.yml
  .github/workflows/config.yml
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  scripts/automator/build/clang-linux_armv7l
  scripts/automator/build/gcc-linux_armv7l
  scripts/automator/build/machine-armv7l
  scripts/automator/build/os-defaults
  scripts/automator/packages/manager-apt
  scripts/automator/packages/manager-brew
  scripts/automator/packages/manager-dnf
  scripts/automator/packages/manager-macports
  scripts/automator/packages/manager-msys2
  scripts/automator/packages/manager-pacman
  scripts/automator/packages/manager-zypper
Labels: CI, enhancement

#240 Make a second, firmer attempt to seek if needed
  src/dos/cdrom_image.cpp
Labels: bug, game compatibility

#249 Update PVS Studio to version 7.06.37052.34
  .github/workflows/analysis.yml
Labels: CI
