Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-01, with the labels that each got.

#110 Reinstate Coverity scanning
  .github/workflows/coverity.yml
Labels: enhancement, external

#119 Create a combined Clang+GCC cache under Windows
  .github/workflows/windows.yml
Labels: enhancement

#123 Redefine fileno for Windows
  include/cross.h
  src/dos/drive_local.cpp
Labels: bug

#121 Add PVS-Studio to our static-analysis workflow
  .github/workflows/analysis.yml
Labels: enhancement

#125 Run config heavy only if our repo has commits
  .github/workflows/config.yml
  .github/workflows/coverity.md
  scripts/has-commits-since.sh
Labels: enhancement

#126 Strip trailing white-space as a pre-commit hook
  scripts/git-prehook-whitespace.sh
Labels: enhancement

#128 Unify Windows installations
  .github/workflows/config.yml
  .github/workflows/windows.yml
Labels: enhancement

#129 Set BASH shell in Config Heavy's commit-check
  .github/workflows/config.yml
Labels: bug

#127 Make downloading packages in the static-opus Makefile more robust and helpful
  contrib/static-opus/Makefile
Labels: enhancement

#130 Count the bugs reported by PVS-Studio
  .github/workflows/analysis.yml
  scripts/count-pvs-bugs.py
Labels: enhancement

#134 Use GNU make < 4.x define syntax
  contrib/static-opus/Makefile
Labels: enhancement

#136 Prevent autoconf from leaking tokens into configure script
  configure.ac
Labels: cleanup

#147 Stamp the PVS analysis directory with time-and-commit details
  .github/workflows/analysis.yml
Labels: cleanup

#140 cga_mono patch
  include/dosbox.h
  include/vga.h
  src/dosbox.cpp
  src/hardware/vga_other.cpp
  src/ints/int10_modes.cpp
  src/shell/shell.cpp
Labels: enhancement

#150 Test more criteria during PVS analysis
  .github/workflows/analysis.yml
  .pvs-suppress
  scripts/count-pvs-bugs.py
Labels: enhancement

#153 Rename snapshot build artifacts
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: enhancement
