Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-06, with the labels that each got.

#414 Add missing commit-checks in platform CI workflow
  .github/workflows/platforms.yml
Labels: CI, bug

#426 Add Ubuntu 20.04 build configurations to CI
  .github/workflows/analysis.yml
  .github/workflows/linux.yml
Labels: CI

#431 Replace ConvDecWord function with atoi/atol
  include/support.h
  src/gui/sdl_mapper.cpp
  src/misc/support.cpp
Labels: cleanup

#432 Expand CI gating with Linux dynrec build
  .github/workflows/linux.yml
Labels: CI

#436 Change mkdir permissions to 775
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
Labels: enhancement

#438 Only suppress non-16-bit initial SB DMA transfers
  src/hardware/sblaster.cpp
Labels: bug

#443 Add Linux x86_64, +dynrec, +debug gating to CI
  .github/workflows/linux.yml
Labels: CI

#441 Further limit criteria for suppressing initial SB DMA transfers
  src/hardware/sblaster.cpp
Labels: bug

#440 Add PIT timer control in mode 3 with a counter of 1 (Paratrooper PC speaker fix)
  src/hardware/timer.cpp
Labels: bug, game compatibility

#452 Avoid strict-aliasing warnings in dynrec
  src/cpu/core_dynrec.cpp
  src/cpu/core_dynrec/decoder_basic.h
Labels: cleanup

#454 Simplify and fix a regression in the PC speaker fade logic
  src/hardware/pcspeaker.cpp
Labels: bug

#456 Ensure SDL2_net preceeds SDL2 in the link-order
  configure.ac
Labels: CI, bug, cleanup

#455 Create initial issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#457 Ensure Tandy DMA partial tail-reads terminate in silence
  src/hardware/tandy_sound.cpp
Labels: bug

#469 [FIXUP] Remove a pointer check when the Tandy DAC mode is changed
  src/hardware/tandy_sound.cpp
Labels: bug
