Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-12, with the labels that each got.

#743 Fix spelling in src/gui/render_crt_glsl.h
  src/gui/render_crt_glsl.h
Labels: cleanup

#744 Fix a build error when compiling with SteamRT default gcc-5.4.0
  src/midi/midi_fluidsynth.cpp
Labels: bug

#757 Sync dr_mp3 with upsteam (v0.6.24)
  src/libs/decoders/dr_mp3.h
Labels: bug, external

#756 Work around MSYS2/MinGW build issues
  include/fs_utils.h
  src/misc/cross.cpp
  src/misc/fs_utils_win32.cpp
  src/misc/support.cpp
Labels: Windows, bug

#761 Update PVS Studio to version 7.10.437
  .github/workflows/pvs-studio.yml
Labels: CI, external

#749 Check and report negotiated audio channels
  src/hardware/mixer.cpp
Labels: SDL2, enhancement

#760 Include FluidSynth statically in the Linux release and test binary
  .github/workflows/linux.yml
Labels: CI, bug

#771 Add 'install' target for pre-rendered png icons
  contrib/icons/.gitignore
  contrib/icons/Makefile
  contrib/icons/icons.md
  contrib/icons/small-png/16x16/dosbox-staging.png
  contrib/icons/small-png/22x22/dosbox-staging.png
  contrib/icons/small-png/24x24/dosbox-staging.png
  contrib/icons/small-png/32x32/dosbox-staging.png
Labels: packaging

#775 Add GitHub Annotations feature to verify-bash.sh
  scripts/verify-bash.sh
Labels: CI, enhancement

#774 Add SPDX tags to mp3_seek_table
  src/libs/decoders/mp3_seek_table.cpp
  src/libs/decoders/mp3_seek_table.h
Labels: documentation

#778 Finishing touches on MT-32 light cleanup
  src/midi/midi_mt32.cpp
Labels: cleanup

#788 Prevent PVS license state from impacting CI results
  .pvs-suppress
Labels: CI, external
