Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-02, with the labels that each got.

#154 Make mappings reloadable
  README
  src/gui/sdl_mapper.cpp
Labels: enhancement

#157 Fix six Coverity and PVS analysis bugs
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
Labels: cleanup

#160 Fix for screenshot handling on PPC
  src/hardware/hardware.cpp
Labels: bug

#179 Workflow fetch script: improve storage layout and allow branch customization
  scripts/fetch-workflows.sh
Labels: enhancement

#183 Fix window positioning
  src/gui/sdlmain.cpp
Labels: bug

#184 CD-DA: fix a pointer invalidation corner-case
  src/dos/cdrom_image.cpp
Labels: bug
