Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-04, with the labels that each got.

#270 Update clang-format rules to 9.0
  .clang-format
  scripts/format-commit.sh
Labels: enhancement

#271 Ensure seeks and reads are within bounds of the track length
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: bug

#273 fixup! Add AUTOTYPE to DOSBox's programs
  src/dos/program_autotype.cpp
Labels: cleanup

#275 Remove a couple erroneous null-pointer assertions
  src/gui/sdl_mapper.cpp
Labels: bug

#276 Fix a number of warnings in ems.cpp
  src/ints/ems.cpp
Labels: cleanup

#286 Fix builds with OpenGL disabled
  src/gui/sdlmain.cpp
Labels: bug

#287 Create byteorder header for host_to_le functions
  include/Makefile.am
  include/byteorder.h
  include/mem.h
  src/hardware/mixer.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: cleanup

#305 Use more robust method to get the scripts directory
  scripts/build.sh
  scripts/list-build-dependencies.sh
Labels: CI

#306 Sync dr_wav with upsteam (v0.12.2)
  src/libs/decoders/dr_wav.h
Labels: bug, external

#320 Add mailmap file to update maintainer information
  .mailmap
Labels: notabug

#309 Sync dr_mp3 with upstream (v0.6.5) to fix a typo
  src/libs/decoders/dr_mp3.h
Labels: Raspberry Pi, bug

#308 Move to GitHub's v2 checkout API
  .github/workflows/analysis.yml
  .github/workflows/config.yml
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/pvs-studio.yml
  .github/workflows/windows.yml
Labels: CI, enhancement

#328 Cleanup and add warning count to platform builds
  .github/workflows/platforms.yml
Labels: CI, cleanup
