Repository dosbox-staging/dosbox-staging, pull requests merged in 2020-10, with the labels that each got.

#644 Append "(debug build)" to the title bar text
  src/gui/sdlmain.cpp
Labels: enhancement

#645 Amend DNF package dependencies per Fedora 32 Workstation needs
  scripts/automator/packages/gcc-dnf
  scripts/automator/packages/manager-dnf
Labels: bug

#649 Replace set-env with new mechanism for updating CI env
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/platforms.yml
  .github/workflows/windows.yml
Labels: CI, bug

#652 Fix space removing in modem ATD command
  src/hardware/serialport/softmodem.cpp
Labels: bug

#675 Bundle VS C++ Runtime Files in Windows package
  .github/workflows/windows.yml
  docs/vc_redist.txt
Labels: Windows, bug

#678 Query glib's version when packaging the macOS snapshot
  .github/workflows/macos.yml
Labels: CI

#625 Make the PC Speaker's DC-offset correction optional
  src/dosbox.cpp
  src/hardware/pcspeaker.cpp
Labels: bug, external

#681 Don't check for glib nor gthread headers
  .github/workflows/macos.yml
  configure.ac
  scripts/automator/packages/manager-dnf
Labels: CI

#680 Add more information to metainfo.xml
  .github/workflows/analysis.yml
  contrib/linux/dosbox-staging.desktop
  contrib/linux/dosbox-staging.metainfo.xml
Labels: documentation, packaging

#687 Use appstream-util for validation
  .github/workflows/analysis.yml
  contrib/linux/dosbox-staging.metainfo.xml
Labels: documentation

#640 Apply the SoftLimiter to FluidSynth
  include/soft_limiter.h
  src/hardware/gus.cpp
  src/midi/midi_fluidsynth.cpp
  src/midi/midi_fluidsynth.h
  tests/soft_limiter.cpp
Labels: bug, enhancement
