Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-06, with the labels that each got.

#1031 Patch for dynamic core on 64-bit systems with W^X
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  meson.build
  src/config.h.in
  src/cpu/core_dyn_x86.cpp
  src/cpu/core_dyn_x86/risc_x64.h
  src/cpu/core_dynrec.cpp
  src/cpu/core_dynrec/operators.h
  src/cpu/core_dynrec/risc_armv8le.h
  src/cpu/dyn_cache.h
Labels: Linux, enhancement, macOS

#1050 Fix an array vs singleton issue in PS/1 Audio flagged by Coverty
  src/hardware/ps1audio.cpp
Labels: bug

#1046 Adjust the `format-commit` script to work natively on macOS
  scripts/format-commit.sh
Labels: macOS

#1054 cleanup a few issues in dyn_cache.h
  src/cpu/dyn_cache.h
Labels: cleanup

#1055 implement W^X logic for Win32
  .github/workflows/macos.yml
  src/cpu/dyn_cache.h
  src/gui/sdlmain.cpp
Labels: enhancement

#1060 Fix regression in r4444: Hercules machine type cursor translation [DOSBox SVN]
  src/ints/int10_char.cpp
  src/ints/int10_modes.cpp
Labels: upstream sync

#1065 Fix and expand thanks to supporters
  THANKS
Labels: documentation

#1059 Use regular expression to expand shell variables
  .github/workflows/windows.yml
  src/shell/shell_misc.cpp
Labels: cleanup

#1067 fix high competing CPU load sluggishness
  src/gui/sdlmain.cpp
Labels: regression

#1074 Filter residfp sources in vs-package solution
  vs/dosbox.vcxproj.filters
Labels: buildsystem

#1076 Sync with upstream r4459
  src/hardware/vga_memory.cpp
Labels: upstream sync

#1078 Sync dr_wav with upstream (v0.12.20)
  src/libs/decoders/dr_wav.h
Labels: upstream sync

#1079 Adjust MT-32 settings based on listening tests
  src/midi/midi_mt32.cpp
Labels: enhancement

#1084 Delay for precise number of milliseconds on supported systems
  include/timer.h
  src/dosbox.cpp
Labels: cleanup

#1086 Fix test crash when using GLIBCXX_ASSERTIONS
  tests/soft_limiter_tests.cpp
Labels: tests

#1093 Fix for issue flagged by Coverty in residfp
  src/libs/residfp/resample/SincResampler.cpp
Labels: cleanup, external

#1092 Mitigate an incorrect optimization by Clang in STB Vorbis
  src/libs/decoders/stb_vorbis.h
Labels: bug, external

#1091 Move the notification about non-standard characters to DEBUG_LOG
  contrib/translations/en/en_US.lng
  contrib/translations/es/es_ES.lng
  contrib/translations/fr/fr_FR.lng
  contrib/translations/it/it_IT.lng
  contrib/translations/ru/ru_RU.lng
  contrib/translations/utf-8/en/en-0.77.0-alpha.txt
  contrib/translations/utf-8/es/es-0.77.0-alpha.txt
  contrib/translations/utf-8/fr/fr-0.77.0-alpha.txt
  contrib/translations/utf-8/it/it-0.77.0-alpha.txt
  contrib/translations/utf-8/ru/ru-0.77.0-alpha.txt
  src/shell/shell.cpp
  src/shell/shell_batch.cpp
Labels: cleanup

#1097 Allow static linking for mt32emu in Meson
  meson.build
Labels: buildsystem
