Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-12, with the labels that each got.

#1417 Drop work-around for previously broken Ruby Cargo installation
  .github/workflows/analysis.yml
Labels: CI

#1418 Test proposed PVS Studio and LGTM fixes in xxHash
  src/libs/decoders/xxhash.h
Labels: upstream sync

#1420 Build x86-64 macOS releases with a 10.15 deployment target
  .github/meson/macos-10.15-deployment-target.ini
  .github/workflows/macos.yml
Labels: macOS, CI

#1421 Sync loguru with upstream (#1416)
  src/libs/loguru/loguru.cpp
Labels: upstream sync

#1422 Update German (de_DE) translation
  contrib/translations/de/de_DE.lng
  contrib/translations/utf-8/de/de-0.78.0-alpha.txt
Labels: translation

#1423 Fix some shaders not working with NN-output
  src/gui/render_glsl.h
Labels: bug

#1424 Workaround bug introduced in the ncurses MSYS2 packages
  .github/workflows/windows-meson-msys2.yml
Labels: CI, buildsystem

#1433 Revert "Workaround bug introduced in the ncurses MSYS2 packages"
  .github/workflows/windows-meson-msys2.yml
Labels: upstream sync

#1432 Update FluidSynth wrap to version 2.2.4 revision 1
  subprojects/fluidsynth.wrap
Labels: upstream sync

#1435 Query the locale for potential language setting
  src/misc/messages.cpp
Labels: translation

#1445 Revert "Refactor mount handling with std::filesystem routines (#1444)"
  include/support.h
  src/dos/dos_programs.cpp
  src/dos/program_mount.cpp
  src/misc/support.cpp
Labels: regression

#1449 Don't log subsequent unhandled port IO calls (#1448)
  src/hardware/iohandler_containers.cpp
  src/hardware/ne2000.cpp
Labels: cleanup

#1452 Cleanup minor LGTM and Coverity issues in IDE
  src/hardware/ide.cpp
Labels: cleanup

#1453 Paramaterize the SB speaker warm-up duration
  src/dosbox.cpp
  src/hardware/sblaster.cpp
Labels: regression

#1454 Always use dosbox-staging.conf regardless of build type
  .github/workflows/dormant/windows-2019.yml
  .github/workflows/windows.yml
  meson.build
  src/config.h.in
  src/misc/cross.cpp
  src/platform/visualc/config.h
Labels: enhancement

#1458 Fix CLS command in VESA modes
  src/shell/shell_cmds.cpp
Labels: enhancement

#1457 Omit 320x200x15/16/24 modes from compatible VESA set
  src/hardware/vga_s3.cpp
Labels: enhancement, game compatibility

#1461 Disable NPOT textures and edge clamping for custom shaders
  src/gui/sdlmain.cpp
Labels: regression

#1465 Sync loguru with upstream (snapshot 2021-12-26)
  src/libs/loguru/loguru.cpp
Labels: regression, arm

#1467 Sync loguru with upstream (snapshot 2021-12-27)
  src/libs/loguru/loguru.cpp
Labels: upstream_sync

#1477 Document gmock dependency installation for Fedora
  BUILD.md
Labels: documentation, backport

#1479 Only use std::filesystem for clang 12.x and up
  include/std_filesystem.h
Labels: macOS, buildsystem, backport
