Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-01, with the labels that each got.

#802 Hibernate PVS Studio until our license is renewed
  .github/workflows/dormant/pvs-studio.yml
Labels: CI, external

#811 Improve use of GCC sanitizers in CI runs
  .github/scripts/build-and-run-sanitizers.sh
  .github/workflows/analysis.yml
  .lsan-suppress
Labels: CI

#825 Move safe_strcpy and safe_strcat to string_utils
  .github/workflows/windows.yml
  include/dos_system.h
  include/hardware.h
  include/string_utils.h
  include/support.h
  src/debug/debug.cpp
  src/debug/debug_gui.cpp
  src/dos/cdrom_image.cpp
  src/dos/dos_files.cpp
  src/dos/dos_keyboard_layout.cpp
  src/dos/dos_programs.cpp
  src/dos/drive_cache.cpp
  src/dos/drive_fat.cpp
  src/dos/drive_iso.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/dos/drives.cpp
  src/dos/program_ls.cpp
  src/hardware/hardware.cpp
  src/hardware/ipx.cpp
  src/hardware/mixer.cpp
  src/hardware/serialport/softmodem.cpp
  src/ints/bios_disk.cpp
  src/midi/midi_alsa.h
  src/midi/midi_oss.cpp
  src/misc/cross.cpp
  src/misc/messages.cpp
  src/misc/setup.cpp
  src/shell/shell.cpp
  src/shell/shell_misc.cpp
  tests/string_utils.cpp
  tests/support.cpp
Labels: cleanup

#831 Update glib to 2.67.2 in static builder
  contrib/static-glib/Makefile
Labels: external

#835 Detect Code Audio, Core MIDI dependencies via Meson
  meson.build
  src/config.h.in
  src/midi/meson.build
Labels: CI

#842 Describe machine types in README and man page
  README
  docs/dosbox.1
Labels: documentation
