Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-03, with the labels that each got.

#924 Check if exit was requested in CHOICE's Read() loop
  src/shell/shell_cmds.cpp
Labels: regression

#917 Add a rote-implemented blocking read-write queue
  include/rwqueue.h
  src/misc/meson.build
  src/misc/rwqueue.cpp
  tests/meson.build
  tests/rwqueue.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: cleanup

#928 Always support Opus CD-DA tracks
  .github/workflows/linux.yml
  BUILD.md
  meson.build
  meson_options.txt
  src/config.h.in
  src/libs/decoders/SDL_sound.c
  src/libs/decoders/meson.build
  src/platform/visualc/config.h
Labels: bug, buildsystem

#934 Don't upload logs unnecessarily
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: CI

#932 Remove "-git" suffix from .conf file in release
  .github/workflows/windows.yml
  meson.build
  src/config.h.in
  src/misc/cross.cpp
  src/platform/visualc/config.h
Labels: bug

#941 Split implementation out of midi_alsa header
  src/midi/meson.build
  src/midi/midi.cpp
  src/midi/midi_alsa.cpp
  src/midi/midi_alsa.h
Labels: cleanup

#942 Add a delay between AUTOTYPE key down and up events
  src/gui/sdl_mapper.cpp
Labels: bug

#958 ALSA MIDI improvements: list filtering, autoconnect (part 3)
  src/midi/midi_alsa.cpp
  src/midi/midi_alsa.h
Labels: Linux, enhancement
