Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-02, with the labels that each got.

#853 Fix increment of unintialized deque iterator in Debug Win-x64 build
  src/misc/setup.cpp
Labels: Windows, bug

#861 Update list of zypper packages
  scripts/automator/packages/manager-zypper
Labels: Linux, buildsystem

#864 Shorten the Moody queue's directory name
  src/libs/rwqueue/LICENSE
  src/libs/rwqueue/README
  src/libs/rwqueue/atomicops.h
  src/libs/rwqueue/readerwritercircularbuffer.h
  tests/readerwritercircularbuffer.cpp
Labels: cleanup

#863 Manage MT-32 rendering and playback using the RW queue
  src/midi/midi_mt32.cpp
  src/midi/midi_mt32.h
Labels: Aarch64, bug, refactorization

#870 Replace deprecated FluidSynth effect calls
  src/midi/midi_fluidsynth.cpp
Labels: cleanup

#872 Adjust VER help message to new style
  src/shell/shell.cpp
Labels: documentation

#877 Ensure the Disney leading-channel is always valid
  src/hardware/disney.cpp
Labels: bug

#886 Backport disabling of OpenMP when building FluidSynth statically (#867)
  contrib/static-fluidsynth/Makefile
Labels: bug

#879 Ensure the Disney leading-channel is always valid
  src/hardware/disney.cpp
Labels: backport, bug

#892 Add pkg-config support to contrib/static-fluidsynth
  contrib/static-fluidsynth/Makefile
Labels: buildsystem

#898 Fix CD-DA pregap start calculation instead of clamping-to-sanity
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: backport, bug

#901 Backport CD-DA pregap start calculation fix to 0.76.x
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: backport, bug

#912 Add a startup verbosity option to only show the splash screen
  contrib/translations/en/en_US.lng
  contrib/translations/fr/fr_FR.lng
  contrib/translations/pl/pl_PL.CP437.lng
  contrib/translations/pl/pl_PL.lng
  contrib/translations/ru/ru_RU.lng
  contrib/translations/utf-8/en/en-0.77.0-alpha.txt
  contrib/translations/utf-8/fr/fr-0.77.0-alpha.txt
  contrib/translations/utf-8/pl/pl-0.77.0-alpha.txt
  contrib/translations/utf-8/ru/ru-0.77.0-alpha.txt
  include/control.h
  src/dosbox.cpp
  src/gui/sdlmain.cpp
  src/misc/programs.cpp
  src/misc/setup.cpp
Labels: enhancement

#868 Refactor code to avoid issues detected by LGTM
  src/hardware/vga_draw.cpp
Labels: cleanup

#911 Let user opt-out of building unit tests
  .github/workflows/linux.yml
  meson_options.txt
  tests/meson.build
Labels: buildsystem

#919 Disambiguate the CONFIG_ROMDIR versus its ROM files
  contrib/translations/en/en_US.lng
  contrib/translations/pl/pl_PL.CP437.lng
  contrib/translations/pl/pl_PL.lng
  contrib/translations/ru/ru_RU.lng
  contrib/translations/utf-8/en/en-0.77.0-alpha.txt
  contrib/translations/utf-8/pl/pl-0.77.0-alpha.txt
  contrib/translations/utf-8/ru/ru-0.77.0-alpha.txt
Labels: documentation
