Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-11, with the labels that each got.

#1355 Fix syntax error
  src/hardware/ne2000.cpp
Labels: bug

#1362 Reset the ALSA snd sequence after halting
  src/midi/midi_alsa.cpp
Labels: regression

#1367 Update PVS Studio to 7.15.53844.172
  .github/workflows/pvs-studio.yml
Labels: CI

#1368 Add help messages for CLS, IF, and SHIFT commands
  src/shell/shell.cpp
Labels: documentation

#1374 Fix Windows CI builds
  .github/workflows/windows.yml
Labels: Windows, CI

#1380 Reduce DOS's change-dir criteria for success
  src/dos/dos_files.cpp
Labels: bug

#1389 Fix zero-offset handling in the PC Speaker (#1386)
  include/mixer.h
  src/hardware/pcspeaker.cpp
Labels: regression

#1406 Check zlib return values in ZMBV (CWE-252)
  src/libs/zmbv/zmbv.cpp
Labels: cleanup

#1407 Document that numlock and caplock are off on startup
  README
  src/gui/sdlmain.cpp
Labels: bug, external, SDL2

#1413 Use FluidSynth wrap version 2.2.3-2
  subprojects/fluidsynth.wrap
Labels: upstream sync
