Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-04, with the labels that each got.

#966 Sync dr_flac with upstream (v0.12.29)
  src/libs/decoders/dr_flac.h
Labels: external

#967 Update mt32emu wrap dependency to 2.5.0
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  meson.build
  subprojects/mt32emu.wrap
Labels: enhancement

#972 Seperate out intro cdrom command for Windows and other OSes. Also add example for mounting cue files.
  src/dos/dos_programs.cpp
Labels: documentation, enhancement

#988 Use the same cache key for Windows debug and release builds
  .github/workflows/windows.yml
Labels: buildsystem
