Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-05, with the labels that each got.

#986 Update FluidSynth wrap to use 2.2.0
  subprojects/fluidsynth.wrap
Labels: buildsystem, enhancement, external

#983 Add pdcurses to the Windows list of vcpkg's in README.md
  docs/build-windows.md
Labels: documentation

#1011 Postfix glib's version with vcpkg's release number
  .github/workflows/windows.yml
Labels: CI, Windows

#1019 Sync Nuked with upstream
  src/libs/nuked/opl3.c
Labels: bug, external

#1024 Reinstate PVS Studio
  .github/workflows/pvs-studio.yml
  .gitignore
Labels: CI

#1029 added tests to VS2019 solution
  .github/workflows/windows.yml
  .gitignore
  src/misc/setup.cpp
  tests/example_tests.cpp
  tests/fs_utils_tests.cpp
  tests/meson.build
  tests/rwqueue_tests.cpp
  tests/setup_tests.cpp
  tests/soft_limiter_tests.cpp
  tests/string_utils_tests.cpp
  tests/stubs.cpp
  tests/support_tests.cpp
  tests/vs/tests.vcxproj
  tests/vs/tests.vcxproj.filters
  vs/dosbox.sln
Labels: buildsystem, tests

#984 Finalize dangling child classes
  include/cpu.h
  include/dos_inc.h
  include/drives.h
  include/serialport.h
  include/setup.h
  include/shell.h
  src/cpu/cpu.cpp
  src/cpu/dyn_cache.h
  src/cpu/paging.cpp
  src/debug/debug.cpp
  src/dos/cdrom.h
  src/dos/dev_con.h
  src/dos/dos_devices.cpp
  src/dos/dos_keyboard_layout.cpp
  src/dos/dos_mscdex.cpp
  src/dos/dos_programs.cpp
  src/dos/drive_fat.cpp
  src/dos/drive_iso.cpp
  src/dos/drive_overlay.cpp
  src/dos/drive_virtual.cpp
  src/dos/program_autotype.h
  src/dos/program_ls.h
  src/gui/sdl_gui.cpp
  src/gui/sdl_mapper.cpp
  src/hardware/cmos.cpp
  src/hardware/dma.cpp
  src/hardware/gameblaster.cpp
  src/hardware/hardware.cpp
  src/hardware/iohandler.cpp
  src/hardware/ipx.cpp
  src/hardware/joystick.cpp
  src/hardware/mame/saa1099.h
  src/hardware/mame/sn76496.h
  src/hardware/memory.cpp
  src/hardware/mixer.cpp
  src/hardware/mpu401.cpp
  src/hardware/ne2000.cpp
  src/hardware/pci_bus.cpp
  src/hardware/pcspeaker.cpp
  src/hardware/pic.cpp
  src/hardware/sblaster.cpp
  src/hardware/serialport/directserial.h
  src/hardware/serialport/nullmodem.h
  src/hardware/serialport/serialdummy.h
  src/hardware/serialport/serialport.cpp
  src/hardware/serialport/softmodem.h
  src/hardware/tandy_sound.cpp
  src/hardware/timer.cpp
  src/hardware/vga_memory.cpp
  src/ints/bios.cpp
  src/ints/ems.cpp
  src/ints/xms.cpp
  src/midi/midi.cpp
  src/midi/midi_alsa.h
  src/midi/midi_coreaudio.h
  src/midi/midi_coremidi.h
  src/midi/midi_oss.h
  src/midi/midi_win32.h
  src/misc/programs.cpp
  src/shell/shell.cpp
Labels: cleanup

#1018 Fix shifting of negative 8-bit samples in `fast` OPL2 mode
  src/hardware/dbopl.cpp
Labels: bug

#995 Avoid stranding the window in fullscreen
  src/gui/sdlmain.cpp
Labels: Raspberry Pi, bug

#1005 Fix shifting of negative 8-bit samples in the mixer
  src/hardware/mixer.cpp
Labels: bug
