Repository dosbox-staging/dosbox-staging, pull requests merged in 2021-07, with the labels that each got.

#1098 Add a bit more documentation regarding Meson options
  BUILD.md
  README.md
Labels: documentation

#1134 Replace match using position-length notation in shell
  src/shell/shell_misc.cpp
Labels: Linux, notabug

#1127 Add yield() to spinlock
  include/timer.h
Labels: cleanup

#1142 Refactor list of shell commands and their usage (addition to `ww/helpcmd`)
  include/shell.h
  src/shell/shell_cmds.cpp
Labels: cleanup

#1126 Cleanup divide-by-zero cases in pixel-perfect
  src/libs/ppscale/ppscale.c
Labels: cleanup

#1146 Sync STB Vorbis codec with upstream version 1.22
  src/libs/decoders/stb_vorbis.h
Labels: upstream sync

#1147 Sync archive serializer with upstream
  src/libs/decoders/archive.h
Labels: upstream sync

#1144 Allow exact window size selection
  src/gui/sdlmain.cpp
Labels: regression

#1149 Only query joysticks for automatic configuration
  src/gui/sdl_mapper.cpp
Labels: backport, regression

#1133 Increase processing tempo of events
  src/gui/sdlmain.cpp
Labels: backport, external, macOS, regression

#1151 Remove vcpkg FluidSynth SF2 files incompatible with GitHub cache
  .github/workflows/windows.yml
Labels: CI

#1145 Log display properties consistently
  src/gui/sdlmain.cpp
Labels: cleanup

#1162 Restore conditional sizing for resizable windows (#1161)
  src/gui/sdlmain.cpp
Labels: backport, regression

#1158 Fix vsync lag
  include/pacer.h
  include/timer.h
  src/gui/sdlmain.cpp
  src/misc/meson.build
  src/misc/pacer.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: bug

#1165 Write messages in the order they were added
  src/misc/messages.cpp
Labels: cleanup

#1166 Allow joystick event mapping when `joysticktype = none`
  README
  include/joystick.h
  src/dosbox.cpp
  src/gui/sdl_mapper.cpp
  src/hardware/joystick.cpp
Labels: bug
