Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-07, with the labels that each got.

#1771 Replace FluidSynth's reverb customization with the mixer's
  src/midi/midi_fluidsynth.cpp
Labels: cleanup

#1777 Add missing #endif that results in compilation error
  contrib/resources/glshaders/crt-easymode-flat.glsl
Labels: regression

#1778 Fix a regression in the discrete PC Speaker affecting Narco Police
  src/hardware/pcspeaker_discrete.cpp
  src/hardware/pcspeaker_discrete.h
Labels: regression

#1784 Don't stop the discrete PC Speaker channel
  src/hardware/pcspeaker_discrete.cpp
  src/hardware/pcspeaker_discrete.h
Labels: regression

#1780 Add configurable softmodem connect speed
  README
  src/dosbox.cpp
  src/hardware/serialport/softmodem.cpp
  src/hardware/serialport/softmodem.h
Labels: enhancement

#1806 Simplify highpass and lowpass filter logging
  src/hardware/mixer.cpp
Labels: cleanup

#1810 Allow calibration of joystick axis timing parameters
  src/dosbox.cpp
  src/hardware/joystick.cpp
Labels: enhancement

#1815 Add MIDI sequence mute/unmute handling
  include/midi.h
  src/hardware/mixer.cpp
  src/midi/midi.cpp
  src/midi/midi_handler.h
Labels: bug

#1817 Stop CHOICE from waiting for input when EOF is reached
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: bug

#1828 Fix queue bug resulting in rough PS/2 mouse movement
  src/ints/mouse.cpp
Labels: bug
