Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-09, with the labels that each got.

#1900 Mixer improvements
  src/hardware/mixer.cpp
Labels: documentation, enhancement

#1894 Resume mixer channels in a clean state (fix pop regression)
  include/mixer.h
  src/hardware/mixer.cpp
Labels: regression

#1902 Use a bool to record if the channel should sleep
  include/mixer.h
  src/hardware/mixer.cpp
Labels: cleanup

#1904 Improve robustness of resolution logging using `get_canvas_size`
  src/gui/sdlmain.cpp
Labels: bug

#1908 Fix CONFIG command's description
  contrib/resources/translations/en.lng
  src/misc/programs.cpp
Labels: documentation, cleanup

#1910 Update Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1914 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1917 Update Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1921 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1924 Update Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1926 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1920 Add Windows installer script and workflow
  .github/workflows/windows-meson-msys2.yml
  .github/workflows/windows.yml
  contrib/icons/dosbox-staging.bmp
  contrib/windows_installer/DOSBox-Staging-setup.iss
Labels: packaging

#1927 Update Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1930 Displays help header for INTRO command
  src/dos/program_intro.cpp
Labels: bug, documentation

#1931 Minor fixes to the Italian translation (it-it)
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1934 Makes DOSBox Staging icons look the same with Windows installer
  contrib/windows_installer/DOSBox-Staging-setup.iss
Labels: enhancement

#1936 Fix mouse wheel for DOS Navigator 2
  src/ints/mouse_dos_driver.cpp
Labels: bug

#1939 Some small changes to the Italian translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1940 Add translated configuration files
  contrib/resources/meson.build
  contrib/resources/translated-0.79-conf-files/dosbox-staging-de.conf
  contrib/resources/translated-0.79-conf-files/dosbox-staging-it.conf
  contrib/resources/translated-0.79-conf-files/dosbox-staging-pl.conf
  contrib/resources/translated-0.79-conf-files/meson.build
Labels: translation

#1938 Better support for piping with builtin Y drive support
  src/shell/shell.cpp
Labels: enhancement

#1949 Removes non-existant KEYB messages
  src/dos/program_keyb.cpp
Labels: cleanup

#1956 Change MIDI config problems into warnings
  src/midi/midi.cpp
  src/midi/midi_fluidsynth.cpp
Labels: cleanup, backport

#1962 Specify library module for FluidSynth dep
  meson.build
Labels: buildsystem

#1958 Codify the use of Semantic Versioning (MAJOR.MINOR.PATCH)
  src/config.h.in
  src/platform/visualc/config.h
Labels: documentation

#1963 Use SpeexDSP from the system if passes tests
  meson.build
Labels: buildsystem, 3rd party package

#1954 Makes Dutch language file default to U.S. keyboard layout
  src/dos/dos_keyboard_layout.cpp
Labels: backport, translation, waiting on: reviewer(s)

#1965 Fix a few mistakes, and convert more escape codes to ansi text
  contrib/resources/translations/en.lng
  contrib/resources/translations/es.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.cp437.CP437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/ru.lng
  contrib/resources/translations/utf-8/en.txt
  contrib/resources/translations/utf-8/es.txt
  contrib/resources/translations/utf-8/fr.txt
  contrib/resources/translations/utf-8/nl.txt
  contrib/resources/translations/utf-8/pl.txt
  contrib/resources/translations/utf-8/ru.txt
Labels: backport, translation

#1974 Cleanup a local string name in the shell line parser
  src/shell/shell.cpp
Labels: cleanup, backport

#1976 Only re-configure the resamplers on rate changes
  src/hardware/mixer.cpp
Labels: regression, backport

#1978 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: backport, translation

#1979 Update Italian (it-it) configuration file
  contrib/resources/translated-0.79-conf-files/dosbox-staging-it.conf
Labels: translation
