Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-05, with the labels that each got.

#1642 Apply clang-format to debugger changes
  src/debug/debug.cpp
  src/debug/debug_gui.cpp
  src/gui/sdlmain.cpp
Labels: cleanup

#1644 Update Coverity scanner to 2021.12.1
  .github/workflows/coverity.yml
Labels: CI

#1643 Enable high DPI for debugger window
  src/libs/PDCurses/sdl2_queue/pdcscrn.cpp
Labels: enhancement

#1645 Fix debug window-event ID check
  src/gui/sdlmain.cpp
Labels: bug

#1641 Render Innovation SSI-2001 samples after write (#1640)
  src/hardware/innovation.cpp
  src/hardware/innovation.h
Labels: regression

#1647 Retain markup messages and render on demand
  src/misc/messages.cpp
Labels: bug, translation

#1653 Update MacPorts dependency names
  docs/build-macos.md
Labels: documentation, macOS, buildsystem

#1654 Fix MIXER indentation
  src/hardware/mixer.cpp
Labels: cleanup

#1649 Shaders can now use sRGB texture or framebuffer via pragmas
  include/render.h
  src/gui/render.cpp
  src/gui/sdlmain.cpp
Labels: enhancement

#1652 Add zlib as a dependency of ZMBV (#1651 part 2/2)
  .github/workflows/macos.yml
  .github/workflows/windows-meson-msys2.yml
  meson.build
  meson_options.txt
  src/hardware/meson.build
  subprojects/zlib.wrap
Labels: macOS, buildsystem

#1664 Use gamma-correct interpolation in shaders that benefit from it
  contrib/resources/glshaders/advinterp2x.glsl
  contrib/resources/glshaders/advinterp3x.glsl
  contrib/resources/glshaders/advmame2x.glsl
  contrib/resources/glshaders/advmame3x.glsl
  contrib/resources/glshaders/none.glsl
  contrib/resources/glshaders/sharp.glsl
Labels: enhancement, external

#1670 Handle --version and --help before loguru init
  src/gui/sdlmain.cpp
Labels: bug

#1693 Mixer command improvements
  src/hardware/mixer.cpp
Labels: bug, documentation

#1691 Don't reset screen on focus gain events
  src/gui/sdlmain.cpp
Labels: cleanup
