Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-11, with the labels that each got.

#2060 Minor mouse enhancements
  include/mouse.h
  include/sdlmain.h
  include/video.h
  src/dos/program_mousectl.cpp
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
  src/hardware/mouse/mouse.cpp
  src/hardware/mouse/mouse_common.cpp
  src/hardware/mouse/mouse_common.h
  src/hardware/mouse/mouse_config.cpp
  src/hardware/mouse/mouse_config.h
  src/hardware/mouse/mouse_interfaces.cpp
  src/hardware/mouse/mouse_interfaces.h
  src/hardware/mouse/mouse_manymouse.cpp
  src/hardware/mouse/mouseif_dos_driver.cpp
  src/hardware/mouse/mouseif_ps2_bios.cpp
  src/hardware/mouse/mouseif_virtual_machines.cpp
Labels: bug, enhancement, cleanup, PR: unreviewed, PR: reviewed-changes-requested

#2062 Add mouse related hints to title bar
  include/sdlmain.h
  include/video.h
  src/dos/program_mousectl.cpp
  src/gui/sdlmain.cpp
  src/hardware/mouse/mouse.cpp
Labels: enhancement, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#2064 Cleanup string IDs of DOS programs
  contrib/resources/translations/de.lng
  contrib/resources/translations/en.lng
  contrib/resources/translations/es.lng
  contrib/resources/translations/fr.lng
  contrib/resources/translations/it.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/ru.lng
  contrib/resources/translations/utf-8/de.txt
  contrib/resources/translations/utf-8/en.txt
  contrib/resources/translations/utf-8/es.txt
  contrib/resources/translations/utf-8/fr.txt
  contrib/resources/translations/utf-8/it.txt
  contrib/resources/translations/utf-8/nl.txt
  contrib/resources/translations/utf-8/pl.txt
  contrib/resources/translations/utf-8/ru.txt
  src/dos/program_autotype.cpp
  src/dos/program_boot.cpp
  src/dos/program_imgmount.cpp
  src/dos/program_intro.cpp
  src/dos/program_keyb.cpp
  src/dos/program_loadfix.cpp
  src/dos/program_loadrom.cpp
  src/dos/program_mem.cpp
  src/dos/program_more.cpp
  src/dos/program_mount.cpp
  src/dos/program_mousectl.cpp
  src/dos/program_placeholder.cpp
  src/dos/program_rescan.cpp
  src/dos/program_serial.cpp
  src/misc/help_util.cpp
  src/shell/shell.cpp
Labels: cleanup, translation, PR: unreviewed, PR: partially-approved

#2068 Fix sentence starting with lower case in MOUNT command help
  src/dos/program_mount.cpp
Labels: cleanup, PR: reviewed-approved

#2065 Improve interactive mouse mapping
  include/mouse.h
  src/dos/program_mousectl.cpp
  src/hardware/mouse/mouse.cpp
  src/hardware/mouse/mouse_config.cpp
  src/hardware/mouse/mouse_interfaces.cpp
  src/hardware/mouse/mouse_interfaces.h
  src/hardware/mouse/mouse_manymouse.cpp
  src/hardware/mouse/mouse_manymouse.h
Labels: enhancement, PR: unreviewed, PR: partially-approved

#2070 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: reviewed-approved

#2071 Sync reSIDfp with upstream
  src/libs/residfp/WaveformCalculator.cpp
  src/libs/residfp/WaveformGenerator.cpp
  src/libs/residfp/WaveformGenerator.h
  src/libs/residfp/resample/test.cpp
Labels: upstream_sync, PR: unreviewed

#2069 Update Tracy to v0.9
  contrib/generate_tracy_header/header_bottom.txt
  contrib/generate_tracy_header/update.sh
  include/tracy.h
  src/cpu/core_dyn_x86.cpp
  src/cpu/core_dynrec.cpp
  src/cpu/core_full.cpp
  src/cpu/core_normal.cpp
  src/cpu/core_simple.cpp
  src/dosbox.cpp
  src/gui/sdlmain.cpp
  src/hardware/mixer.cpp
  subprojects/tracy.wrap
Labels: buildsystem, upstream_sync, PR: unreviewed, PR: reviewed-approved

#2079 Use MORE engine for help output
  include/shell.h
  src/dos/meson.build
  src/dos/program_autotype.cpp
  src/dos/program_boot.cpp
  src/dos/program_imgmount.cpp
  src/dos/program_intro.cpp
  src/dos/program_keyb.cpp
  src/dos/program_loadfix.cpp
  src/dos/program_loadrom.cpp
  src/dos/program_mem.cpp
  src/dos/program_more.cpp
  src/dos/program_more.h
  src/dos/program_more_output.cpp
  src/dos/program_more_output.h
  src/dos/program_mount.cpp
  src/dos/program_mousectl.cpp
  src/dos/program_placeholder.cpp
  src/dos/program_rescan.cpp
  src/dos/program_serial.cpp
  src/misc/programs.cpp
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: enhancement, PR: unreviewed

#2088 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2087 Restore 0.79.1 mouse acceleration model in DOS driver
  src/hardware/mouse/mouse_config.h
  src/hardware/mouse/mouseif_dos_driver.cpp
Labels: bug, PR: unreviewed, PR: reviewed-approved

#2086 Refactor ReelMagic player with per-stream handle registration
  include/reelmagic.h
  src/hardware/reelmagic/driver.cpp
  src/hardware/reelmagic/player.cpp
  src/hardware/reelmagic/video_mixer.cpp
Labels: refactorization, PR: reviewed-approved

#2091 Restore WheelHasMoved bit in DOS mouse driver to correct value
  src/hardware/mouse/mouseif_dos_driver.cpp
Labels: regression, PR: unreviewed, PR: reviewed-approved

#2094 Fix character D6 mapping in code page 3021 (Bulgarian MIK encoding)
  contrib/resources/mapping-wikipedia.org/CP_3021.TXT
Labels: bug, translation, PR: reviewed-approved
