Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-08, with the labels that each got.

#1829 (draft for testing) Flag Intel's Windows OpenGL driver as having unreliable sRGB
  src/gui/sdlmain.cpp
Labels: external, Windows

#1832 Remove `magic_enum` due to cons outweighing pros
  LICENSE
  include/enum.h
  src/dos/dos_memory.cpp
  src/hardware/mixer.cpp
  src/libs/magic_enum/LICENSE
  src/libs/magic_enum/README.md
  src/libs/magic_enum/include/magic_enum.hpp
  src/libs/magic_enum/include/magic_enum_format.hpp
  src/libs/magic_enum/include/magic_enum_fuse.hpp
Labels: cleanup

#1833 Partially fix Ultima Underworld mouse issues
  src/ints/mouse.cpp
  src/ints/mouse_core.h
  src/ints/mouse_dos_driver.cpp
Labels: bug

#1836 Log modes 11h and 12h as VGA instead of EGA
  include/vga.h
  src/gui/sdlmain.cpp
  src/hardware/vga.cpp
Labels: cleanup

#1838 Fix texture renderer selection
  src/gui/sdlmain.cpp
Labels: regression

#1850 Mouse code simplification, fix for rare cases of stuck "fire" in DOOM
  src/ints/mouse.cpp
  src/ints/mouse_core.h
  src/ints/mouse_dos_driver.cpp
Labels: bug, cleanup

#1851 Use a shared pointer to ref-count residfp's matrix data
  src/libs/residfp/array.h
Labels: regression

#1855 Fix buffer overflow that happens when processing the very first sample
  src/libs/tal-chorus/Chorus.h
Labels: bug

#1856 Correctly report PNG support in Meson summary
  meson.build
Labels: buildsystem

#1860 Fix seamless mouse on macOS
  src/gui/sdlmain.cpp
Labels: regression

#1861 Fix frames and update KEYB help in Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1863 Reduce MIDI rendering chunk sizes
  src/midi/midi_fluidsynth.cpp
  src/midi/midi_fluidsynth.h
  src/midi/midi_mt32.cpp
  src/midi/midi_mt32.h
Labels: cleanup

#1871 Restore bottom six channel output to CMS/Gameblaster emulation
  src/hardware/gameblaster.cpp
Labels: regression

#1876 Add Polish (pl) translation for CONFIG_AUTOMOUNT
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1878 Use `DOSBox Staging.app` on macOS per Human Interface Guidelines
  .github/workflows/macos.yml
  README
  contrib/macos/create-app-bundle.sh
  scripts/create-package.sh
Labels: macOS, packaging

#1881 Fix several punctuation mistakes in Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#1883 Require a mouse to open the event mapper UI
  include/video.h
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
Labels: SDL2

#1890 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#1891 Update Polish (pl) translation
  contrib/resources/translations/pl.cp437.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation
