Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-02, with the labels that each got.

#1554 Fix bug in shell redirection
  src/shell/shell.cpp
Labels: bug

#1565 Fix a range-check typo in bit operations
  include/bitops.h
Labels: bug

#1564 Revert to physical memory calls for DMA transfers (#1563)
  src/hardware/dma.cpp
Labels: regression

#1567 Assure gtest and gmock in the same version
  tests/meson.build
Labels: tests

#1566 Avoid loading duplicate config files
  include/control.h
  src/misc/setup.cpp
Labels: enhancement

#1570 Fix Visual Studio Dosbox project filters
  vs/dosbox.vcxproj.filters
Labels: regression

#1572 Improve the bit operations compile-time checks and fix the `*_to` argument ordering
  include/bitops.h
  tests/bitops_tests.cpp
Labels: bug, cleanup

#1581 Bump the VC redistibutable package to version 14.31.31103
  .github/workflows/windows.yml
Labels: Windows, CI

#1585 Update feature section in README.md
  README.md
Labels: documentation
