Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-12, with the labels that each got.

#2095 Improve management of audio devices
  include/hardware.h
  include/mixer.h
  src/dos/cdrom_image.cpp
  src/hardware/gameblaster.cpp
  src/hardware/gus.cpp
  src/hardware/innovation.cpp
  src/hardware/lpt_dac.cpp
  src/hardware/mixer.cpp
  src/hardware/opl.cpp
  src/hardware/opl.h
  src/hardware/pcspeaker_discrete.cpp
  src/hardware/pcspeaker_impulse.cpp
  src/hardware/ps1audio.cpp
  src/hardware/reelmagic/player.cpp
  src/hardware/sblaster.cpp
  src/hardware/tandy_sound.cpp
  src/midi/midi_fluidsynth.cpp
  src/midi/midi_mt32.cpp
Labels: PR: partially-approved

#2098 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: unreviewed

#2100 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
  contrib/resources/translations/utf-8/nl.txt
Labels: translation

#2102 Fix tab handling in MORE command
  src/dos/program_more_output.cpp
  src/dos/program_more_output.h
Labels: bug, PR: unreviewed, PR: partially-approved

#2108 Check file-descriptor dependency for Enet, slirp, and ManyMouse
  meson.build
Labels: buildsystem, PR: unreviewed

#2104 Cleanup overcomplicated data conversions in Unicode support
  src/misc/unicode.cpp
Labels: cleanup, PR: reviewed-approved

#2115 Avoid shifting negative DAC data in Sound Blaster #2113 (CWE-758)
  src/hardware/sblaster.cpp
Labels: bug

#2116 Use a `sdd::unique_ptr` to manage the video memory
  include/support.h
  src/hardware/vga_memory.cpp
  src/misc/support.cpp
Labels: PR: unreviewed

#2118 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: unreviewed

#2105 Enable DPI scaling on Windows
  src/gui/sdlmain.cpp
Labels: PR: partially-approved

#2117 Use shared pointers to manage the virtual files
  include/drives.h
  src/dos/drive_virtual.cpp
Labels: bug, PR: unreviewed, PR: partially-approved

#2119 Remove errorneous screen parameters check in mouse code
  src/hardware/mouse/mouse.cpp
Labels: bug, PR: unreviewed, PR: partially-approved

#2120 Update Russian (ru-RU) translation
  contrib/resources/translations/utf-8/ru.txt
Labels: translation, PR: unreviewed

#2124 Drop architecture spec from setup-msbuild GitHub action
  .github/workflows/windows-msvc.yml
Labels: bug, CI, PR: unreviewed

#2125 Add modem call warm-up period
  src/hardware/serialport/softmodem.cpp
  src/hardware/serialport/softmodem.h
Labels: bug, PR: unreviewed

#2132 Update Russian (ru-RU) translation
  contrib/resources/translations/ru.lng
  contrib/resources/translations/utf-8/ru.txt
Labels: translation, PR: unreviewed

#2126 Improve build instructions
  BUILD.md
  README.md
  docs/build-macos.md
  docs/build-windows.md
Labels: documentation, PR: unreviewed, PR: partially-approved

#2133 Fix FluidSynth reverb and chorus settings not applying
  src/midi/midi_fluidsynth.cpp
Labels: bug, PR: unreviewed

#2127 Customise the looks of the macOS DMG distribution disk image
  contrib/macos/DS_Store
  contrib/macos/README.md
  contrib/macos/Start DOSBox Staging.command
  contrib/macos/background/background-1x.png
  contrib/macos/background/background-2x.png
  contrib/macos/background/background.svg
  contrib/macos/background/background.tiff
  contrib/macos/background/merge-background.sh
  contrib/macos/create-app-bundle.sh
  scripts/create-package.sh
Labels: macOS, packaging, PR: unreviewed, PR: partially-approved

#2139 Always use VFR presentation mode for text modes
  src/gui/sdlmain.cpp
Labels: regression, PR: unreviewed, PR: partially-approved

#2130 simplifies file search in virtual drive
  include/drives.h
  src/dos/drive_virtual.cpp
Labels: refactorization, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#2143 Capture the OpenGL screenshot using RGBA pixel format
  src/gui/sdlmain.cpp
Labels: bug, PR: unreviewed, PR: partially-approved

#2141 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
  contrib/resources/translations/utf-8/nl.txt
Labels: translation, PR: unreviewed

#2146 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation, PR: unreviewed

#2147 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: unreviewed

#2145 Dedupe the now-redundant CRT shaders' filename prefixes
  LICENSE
  contrib/resources/glshaders/crt/aperture.glsl
  contrib/resources/glshaders/crt/caligari.glsl
  contrib/resources/glshaders/crt/easymode.glsl
  contrib/resources/glshaders/crt/easymode.tweaked.glsl
  contrib/resources/glshaders/crt/fakelottes.glsl
  contrib/resources/glshaders/crt/fakelottes.tweaked.glsl
  contrib/resources/glshaders/crt/geom.glsl
  contrib/resources/glshaders/crt/geom.tweaked.glsl
  contrib/resources/glshaders/crt/hyllian-updated.glsl
  contrib/resources/glshaders/crt/hyllian.glsl
  contrib/resources/glshaders/crt/lottes-fast.glsl
  contrib/resources/glshaders/crt/lottes-fast.subtle+gain.glsl
  contrib/resources/glshaders/crt/lottes.glsl
  contrib/resources/glshaders/crt/lottes.tweaked.glsl
  contrib/resources/glshaders/crt/mattias.glsl
  contrib/resources/glshaders/crt/pi-vertical.glsl
  contrib/resources/glshaders/crt/pi.glsl
  contrib/resources/glshaders/crt/yee64.glsl
  contrib/resources/glshaders/crt/yeetron.glsl
  contrib/resources/glshaders/crt/zfast-composite.glsl
  contrib/resources/glshaders/crt/zfast.glsl
  src/dosbox.cpp
  src/gui/render.cpp
Labels: cleanup, packaging, PR: unreviewed, PR: reviewed-approved

#2142 Add missing Windows 11 features to MORE command
  include/dos_inc.h
  include/string_utils.h
  src/dos/dos.cpp
  src/dos/program_more.cpp
  src/dos/program_more.h
  src/dos/program_more_output.cpp
  src/dos/program_more_output.h
  src/misc/string_utils.cpp
Labels: enhancement, PR: partially-approved

#2161 Fix imprecise help string in MORE command
  src/dos/program_more.cpp
Labels: bug, PR: unreviewed

#2159 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: unreviewed

#2162 Bump Coverity to v2022.06 (Updated August 14th, 2022)
  .github/workflows/coverity.md
  .github/workflows/coverity.yml
Labels: CI, backport, PR: unreviewed

#2163 Improve seamless mouse configuration entry description, mention the touchscreen
  src/hardware/mouse/mouse_config.cpp
Labels: documentation, backport, PR: partially-approved

#2164 Update Dutch (nl) translation of MORE
  contrib/resources/translations/nl.lng
  contrib/resources/translations/utf-8/nl.txt
Labels: translation, PR: reviewed-approved

#2166 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation, PR: unreviewed

#2172 Change mouse capture default to 'onclick'
  src/hardware/mouse/mouse_config.cpp
Labels: bug, backport, PR: reviewed-approved

#2173 Center mouse cursor before releasing it
  include/video.h
  src/gui/sdlmain.cpp
  src/hardware/mouse/mouse.cpp
Labels: enhancement, backport, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#2181 Use presence of desktop environment in mouse capture states
  include/video.h
  src/gui/sdlmain.cpp
  src/hardware/mouse/mouse.cpp
Labels: bug, Raspberry Pi, backport, PR: unreviewed, PR: partially-approved
