Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-01, with the labels that each got.

#1493 Fix regression that disables keyboard input when using the debugger (#1487)
  src/misc/messages.cpp
Labels: regression, backport

#1500 Prevent `-exit` and `-c exit` command-line arguments from early-exiting
  src/shell/shell.cpp
Labels: regression, backport

#1507 Fix crash when loading UPX-packed code-page file (#1506)
  src/dos/dos_keyboard_layout.cpp
Labels: regression, backport

#1511 MSYS2 build improvements. Switch to Clang 64-bit release build
  .github/workflows/windows-meson-msys2.yml
Labels: Windows, CI

#1513 Fix multi-line command lines
  src/shell/shell_misc.cpp
Labels: bug

#1515 Revert the mixer latency settings on Windows platforms
  src/dosbox.cpp
Labels: Windows, regression

#1522 Replace enum casts in NE2000 with enum_val() helper
  src/hardware/ne2000.cpp
Labels: cleanup

#1523 Catch two overruns in the code-page handler flagged by Coverity
  src/dos/dos_keyboard_layout.cpp
Labels: cleanup

#1527 Support for window transparency
  src/gui/sdlmain.cpp
Labels: enhancement

#1531 Remove default titles from issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: CI

#1529 Fix regression when pixel-perfect scaling low-res VGA modes (#1526)
  src/gui/sdlmain.cpp
Labels: regression

#1535 Convert ANSI codes to markups in help messages
  src/dos/dos_programs.cpp
  src/shell/shell.cpp
Labels: documentation, enhancement

#1539 Fix a regression in the `windowresolution = ` preset size determination
  src/gui/sdlmain.cpp
Labels: regression

#1537 Set joystick illuminator color based on status (#1248)
  include/rgb24.h
  src/gui/sdl_mapper.cpp
Labels: SDL2

#1550 Fix return code in FileOpen
  src/dos/dos_files.cpp
Labels: bug
