Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-06, with the labels that each got.

#1705 Implement CMS / Game Blaster filtering
  src/dosbox.cpp
  src/hardware/gameblaster.cpp
  src/hardware/gameblaster.h
Labels: enhancement

#1702 Make help category headings translatable
  include/help_util.h
  src/misc/help_util.cpp
  src/shell/shell.cpp
Labels: translation

#1709 Fix crash during `output =` transitions
  src/gui/sdlmain.cpp
Labels: bug

#1711 Add an explicit copy constructor to bit_view and a couple more tests
  include/bit_view.h
  tests/bit_view_tests.cpp
Labels: cleanup

#1712 Add per-file code checks using helper macros
  include/checks.h
Labels: plumbing

#1714 Make memory arrays static
  include/mem.h
  include/vga.h
  src/hardware/memory.cpp
  src/hardware/vga_memory.cpp
Labels: cleanup, refactorization

#1713 Add checks for potential narrowing in ZMBV
  src/libs/zmbv/zmbv.cpp
  src/libs/zmbv/zmbv.h
Labels: cleanup

#1721 De-Bitu LazyFlags and PageHandler
  include/paging.h
  src/cpu/core_dyn_x86/decoder.h
  src/cpu/core_dynrec/decoder_basic.h
  src/cpu/core_dynrec/dyn_fpu.h
  src/cpu/core_dynrec/risc_armv8le.h
  src/cpu/flags.cpp
  src/cpu/lazyflags.h
  src/cpu/paging.cpp
  src/debug/debug.cpp
  src/hardware/iohandler.cpp
  src/hardware/memory.cpp
Labels: cleanup

#1730 Remove mixer mutex
  src/hardware/mixer.cpp
Labels: cleanup

#1737 Initialize A20 memory properly
  src/hardware/memory.cpp
Labels: regression

#1739 Catch IIR's potential exception AdlibGold during setup
  src/hardware/adlib_gold.cpp
  src/hardware/adlib_gold.h
Labels: cleanup

#1740 Prevent SB 8-bit stereo DMA from adding zero frames
  src/hardware/sblaster.cpp
Labels: bug

#1746 Remove the SoftLimiter and related buffers from GUS
  src/hardware/gus.cpp
Labels: cleanup, refactorization

#1748 Fix for wrong VMware port IO width
  src/ints/mouse_vmware.cpp
Labels: bug

#1750 Sync GUS interrupt handling from PiGUS
  src/hardware/gus.cpp
Labels: enhancement, peer_sync

#1753 Only include the debugger's dependencies when its enabled
  meson.build
Labels: buildsystem

#1754 Move mouse parameters update
  src/gui/sdlmain.cpp
Labels: regression

#1761 Drop the libspeexdsp workaround for vcpkg
  vs/dosbox.vcxproj
Labels: Windows, buildsystem

#1765 Sync reSIDfp with upstream
  src/libs/residfp/Filter8580.cpp
  src/libs/residfp/resample/SincResampler.cpp
Labels: upstream_sync

#1763 Standardize the OPL rendering routines
  src/hardware/opl.cpp
  src/hardware/opl.h
Labels: refactorization
