Repository dosbox-staging/dosbox-staging, pull requests merged in 2022-03, with the labels that each got.

#1568 Rely on gmock dependency setting up gtest
  BUILD.md
  tests/meson.build
Labels: tests

#1589 Support for changing output options at run-time
  include/video.h
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
Labels: enhancement

#1605 Make last pixel conditional in S3 polygon drawing routines
  src/hardware/vga_xga.cpp
Labels: bug
