Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-01, with the labels that each got.

#2186 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: backport, translation, PR: unreviewed, PR: reviewed-approved

#2187 Fix logging of some pre-EGA modes
  include/vga.h
  src/gui/sdlmain.cpp
  src/hardware/vga.cpp
Labels: bug, backport, PR: unreviewed, PR: partially-approved

#2194 Update Polish (pl) translation, for 0.80.x only
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation, PR: unreviewed, PR: reviewed-approved

#2197 Update Readme.md to add pkgconfig for Arch Linux
  README.md
Labels: bug, documentation, buildsystem, PR: unreviewed, PR: reviewed-approved

#2216 Sync flatpak metadata up to `0.81.0-alpha`
  contrib/linux/dosbox-staging.metainfo.xml
Labels: packaging

#2226 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2225 Fix Tandy support for Ninja (1986)
  src/ints/bios.cpp
Labels: bug

#2227 Improve MIDI buffer underrun logging
  src/midi/midi_fluidsynth.cpp
  src/midi/midi_fluidsynth.h
  src/midi/midi_mt32.cpp
  src/midi/midi_mt32.h
Labels: cleanup

#2209 Handle OEM102 and ABNT1 keyboard scancodes
  contrib/sdl_key_logger/README.md
  include/bios.h
  include/keyboard.h
  src/gui/sdl_mapper.cpp
  src/hardware/keyboard.cpp
  src/ints/bios_keyboard.cpp
Labels: regression, backport

#2239 Add wrap for SDL2 to support static macos builds
  meson.build
  src/gui/meson.build
  subprojects/.gitignore
  subprojects/libjpeg-turbo.wrap
  subprojects/libpng.wrap
  subprojects/sdl2_image.wrap
Labels: macOS, buildsystem

#2242 Add `iir` to the set of MSYS2 packages
  .github/workflows/windows-msys2.yml
  packages/windows-msys2-clang-i686.txt
  packages/windows-msys2-clang-x86_64.txt
  packages/windows-msys2-gcc-i686.txt
  packages/windows-msys2-gcc-x86_64.txt
Labels: buildsystem

#2241 Make conf path handling more robust
  src/misc/cross.cpp
Labels: bug, Linux, backport

#2244 Add note about InnoSetup
  website/docs/downloads/windows.md
Labels: documentation, Windows, packaging

#2245 Update Windows SSL certificate authority in MSYS2 workflow
  .github/workflows/windows-msys2.yml
Labels: help wanted, CI, backport

#2251 Mark all core run functions with `noexcept`
  include/cpu.h
  src/cpu/core_dyn_x86.cpp
  src/cpu/core_dynrec.cpp
  src/cpu/core_full.cpp
  src/cpu/core_normal.cpp
  src/cpu/core_prefetch.cpp
  src/cpu/core_simple.cpp
  src/cpu/cpu.cpp
  src/cpu/dyn_cache.h
Labels: plumbing

#2254 Only unmute / unpause when Window focus is gained
  src/gui/sdlmain.cpp
Labels: bug, backport

#2259 Sync residfp with 2.4.2
  src/libs/residfp/FilterModelConfig6581.h
  src/libs/residfp/Integrator6581.h
  src/libs/residfp/SID.cpp
  src/libs/residfp/WaveformCalculator.cpp
  src/libs/residfp/resample/test.cpp
Labels: upstream_sync
