Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-12, with the labels that each got.

#3167 Fix website development build download page
  website/docs/downloads/development-builds.md
Labels: website

#3168 Website - dev builds query improvement
  website/docs/downloads/development-builds.md
Labels: bug, website

#3171 Do not set icon at runtime
  src/gui/icon.c
  src/gui/sdlmain.cpp
Labels: plumbing

#3172 Adaptive CRT shader compatibility fixes for really old GPUs
  contrib/resources/glshaders/crt/arcade-1080p.glsl
  contrib/resources/glshaders/crt/arcade-1440p.glsl
  contrib/resources/glshaders/crt/arcade-4k.glsl
  contrib/resources/glshaders/crt/arcade-sharp-1080p.glsl
  contrib/resources/glshaders/crt/arcade-sharp-1440p.glsl
  contrib/resources/glshaders/crt/arcade-sharp-4k.glsl
  contrib/resources/glshaders/crt/cga-1080p.glsl
  contrib/resources/glshaders/crt/cga-1440p.glsl
  contrib/resources/glshaders/crt/cga-4k.glsl
  contrib/resources/glshaders/crt/cga-720p.glsl
  contrib/resources/glshaders/crt/composite-1080p.glsl
  contrib/resources/glshaders/crt/composite-1440p.glsl
  contrib/resources/glshaders/crt/composite-4k.glsl
  contrib/resources/glshaders/crt/ega-1080p.glsl
  contrib/resources/glshaders/crt/ega-1440p.glsl
  contrib/resources/glshaders/crt/ega-4k.glsl
  contrib/resources/glshaders/crt/ega-720p.glsl
  contrib/resources/glshaders/crt/hercules.glsl
  contrib/resources/glshaders/crt/monochrome-hires.glsl
  contrib/resources/glshaders/crt/monochrome-lowres.glsl
  contrib/resources/glshaders/crt/vga-1080p-fake-double-scan.glsl
  contrib/resources/glshaders/crt/vga-1080p.glsl
  contrib/resources/glshaders/crt/vga-1440p.glsl
  contrib/resources/glshaders/crt/vga-4k.glsl
Labels: bug, shaders, video

#3174 Let Meson use a system call to detect the page size
  contrib/pagesize/posix_pagesize.c
  contrib/pagesize/windows_pagesize.c
  meson.build
  meson_options.txt
Labels: build system

#3175 Update Coverity to version 2023.6.2
  .github/workflows/coverity.md
  .github/workflows/coverity.yml
Labels: CI

#3164 Country support improvements
  contrib/linux/bash-completion/dosbox
  docs/dosbox.1
  include/control.h
  include/cross.h
  include/dos_inc.h
  src/dos/dos.cpp
  src/dos/dos_keyboard_layout.cpp
  src/dos/dos_locale.cpp
  src/dos/dos_locale.h
  src/dos/meson.build
  src/dosbox.cpp
  src/gui/sdlmain.cpp
  src/misc/setup.cpp
  src/shell/shell_cmds.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: enhancement

#3176 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3111 Clean up OpenGL attribute init
  src/gui/sdlmain.cpp
Labels: cleanup

#3182 Add countries and historic locales from OS/2 Warp 4.52
  src/dos/dos_locale.cpp
Labels: enhancement

#3187 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
Labels: translation

#3192 Improve the "mode 1" deinterlace method
  contrib/resources/glshaders/misc/fixvideo.glsl
Labels: shaders, video

#3194 Only capture the visible image in rendered image capture mode
  include/sdlmain.h
  src/gui/sdlmain.cpp
Labels: bug, video

#3197 Cleanup a couple unhandled switch cases when OpenGL isn't available
  src/gui/sdlmain.cpp
Labels: cleanup

#3190 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3203 Use std math functions in `compressor.cpp`
  src/hardware/compressor.cpp
Labels: plumbing

#3204 docs: Update MkDocs to 9.5.2
  contrib/documentation/mkdocs-package-requirements.txt
Labels: website

#3200 Add deinterlacing shader variants
  contrib/resources/glshaders/misc/fixvideo-scanlines.glsl
  contrib/resources/glshaders/misc/fixvideo.glsl
Labels: enhancement, shaders, video

#3205 Fix description of the `imfc_filter` setting
  src/hardware/imfc.cpp
Labels: audio

#3209 Fix infinite recursion problem at startup on Pop OS 22.04 and SDL 2.0.20
  src/gui/sdlmain.cpp
Labels: bug, SDL, video

#3217 Always clamp `frames_needed` to the allowed mix/max range in the mixer
  src/hardware/mixer.cpp
Labels: regression, audio

#3213 Update translation guide
  contrib/resources/translations/README.md
Labels: documentation

#3216 Allow FROUND fix on x64
  src/fpu/fpu_instructions.h
Labels: bug, FPU emulation

#3214 Display 'max limit' cycles setting properly in the title bar
  src/gui/sdlmain.cpp
Labels: bug

#3219 Fix 'auto' presentation mode on macOS in fullscreen
  src/gui/sdlmain.cpp
Labels: bug

#3223 Remove PSP name from window titlebar
  src/dos/dos_execute.cpp
  src/gui/sdlmain.cpp
Labels: enhancement

#3220 Log display mode correctly on fullscreen/windowed switch & window resize
  src/gui/sdlmain.cpp
  src/gui/shader_manager.cpp
Labels: bug, video

#3224 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3225 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
Labels: translation

#3231 Restore the previous behaviour of pixel art upscaler shaders
  contrib/resources/glshaders/scaler/advinterp2x.glsl
  contrib/resources/glshaders/scaler/advinterp3x.glsl
  contrib/resources/glshaders/scaler/advmame2x.glsl
  contrib/resources/glshaders/scaler/advmame3x.glsl
Labels: regression, shaders, video

#3230 Improve `shell_history_file` setting description
  src/dosbox.cpp
Labels: enhancement, DOS

#3241 Log warning to console when not using full FPU 80-bit precision
  src/fpu/fpu.cpp
Labels: enhancement

#3245 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3246 Update german translation for 0.81 Release
  contrib/resources/translations/de.lng
Labels: translation

#3253 Update Getting Started guide for v0.81.0
  website/docs/getting-started/advanced-graphics-options.md
  website/docs/getting-started/beneath-a-steel-sky.md
  website/docs/getting-started/enhancing-prince-of-persia.md
  website/docs/getting-started/introduction.md
  website/docs/getting-started/next-steps.md
  website/docs/getting-started/passport-to-adventure.md
  website/docs/getting-started/setting-up-prince-of-persia.md
  website/docs/getting-started/star-wars-dark-forces.md
  website/docs/releases/release-notes/0.81.0-rc.md
  website/mkdocs.yml
Labels: documentation

#3247 Fix two PVS Studio warnings
  .github/workflows/pvs-studio.yml
  src/gui/sdlmain.cpp
  src/hardware/vga_s3.cpp
Labels: cleanup, plumbing

#3254 Fix icon install path
  contrib/icons/meson.build
Labels: bug, build system, backport

#3256 Update Italian (it_IT) translation
  contrib/resources/translations/it.lng
Labels: backport, translation

#3250 Render video lines one-by-one even in high resolution modes
  src/hardware/vga_draw.cpp
Labels: enhancement, regression, backport, video

#3263 Fix macOS Info.plist template so the actual version is shown
  contrib/macos/Info.plist.template
Labels: packaging

#3265 Fix Windows-specific 'Crystal Caves' game save problem
  src/misc/fs_utils_win32.cpp
Labels: bug, regression, backport

#3267 Fix broken check for existing file in `localDrive::FileCreate`
  src/dos/drive_local.cpp
Labels: bug, regression, backport

#3272 Remove some 'fast math' release build settings
  meson.build
Labels: bug

#3269 Do not record successive duplicate commands in the history
  src/shell/shell_misc.cpp
Labels: enhancement, backport, DOS

#3274 Enable expect_death tests only in debug builds
  tests/rect_tests.cpp
Labels: tests, backport

#3271 Use UTF-8 for shell history
  include/shell.h
  src/shell/shell.cpp
  src/shell/shell_misc.cpp
Labels: backport, localisation

#3270 Flatten the zlib-ng checks and add explanations
  meson.build
Labels: build system, backport

#3258 Do not read shell history if secure mode is enabled
  src/shell/shell.cpp
Labels: bug, backport, DOS

#3276 Update german translation
  contrib/resources/translations/de.lng
Labels: backport, translation

#3281 Fix a couple of FPU emulation issues
  include/fpu.h
  src/cpu/core_dynrec/dyn_fpu.h
  src/fpu/fpu.cpp
Labels: bug, FPU emulation, backport

#3282 Detect a fatal build combination in Meson
  meson.build
Labels: regression, build system, backport

#3283 Remove obsolete check for forbidden paths on POSIX systems
  include/cross.h
  meson.build
  src/config.h.in
  src/dos/drive_fat.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/dos/program_boot.cpp
  src/hardware/reelmagic/driver.cpp
  src/misc/cross.cpp
  src/misc/fs_utils_posix.cpp
  src/misc/fs_utils_win32.cpp
Labels: bug, backport

#3291 Add header guard to semaphore.h
  include/semaphore.h
Labels: cleanup

#3292 Fix lookup of mapper files from resources
  src/misc/support.cpp
Labels: regression, backport

#3297 Update german translation for v0.81 RC1
  contrib/resources/translations/de.lng
Labels: backport, translation

#3296 Pass button press events to guest side if gaining focus in seamless mode
  src/gui/sdlmain.cpp
Labels: bug, backport
