Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-09, with the labels that each got.

#2810 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#2815 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2818 Refine when `presentation mode = auto` uses throttled mode
  src/gui/sdlmain.cpp
Labels: video

#2822 Prevent duplicate SDL Window creation when using OpenGL
  src/gui/sdlmain.cpp
Labels: regression

#2828 Fix ppc64le backend and 64K page size support
  include/support.h
  meson.build
  src/cpu/core_dynrec/risc_ppc64le.h
  src/cpu/dyn_cache.h
Labels: bug

#2824 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
  contrib/resources/translations/utf-8/nl.txt
Labels: translation

#2840 Fix fallback shader scaling for adaptive CRT shaders
  src/gui/shader_manager.cpp
Labels: bug, shaders, video

#2842 Add support for disabling screen via the clocking mode register, fixes #2838
  src/hardware/vga_draw.cpp
Labels: bug, video

#2843 Always clamp 'frames_needed' to the allowed mix/max range in the mixer
  src/hardware/mixer.cpp
Labels: bug, audio

#2850 Don't sign extend 16-bit immediates to 32-bit in ppc64le dynrec, fixes #2846
  src/cpu/core_dynrec/risc_ppc64le.h
Labels: bug

#2852 Fix the aspect ratio of 40-column 00h and 01h BIOS text modes
  src/hardware/vga_draw.cpp
Labels: regression, video

#2859 Fix spelling mistakes in 'voodoo_*' config descriptions
  src/dosbox.cpp
Labels: documentation, voodoo

#2863 Fix null pointer de-reference in dyncache on Windows
  src/cpu/dyn_cache.h
Labels: regression

#2867 Fix flicker in some games due to mouse driver breaking double buffering
  src/hardware/input/mouseif_dos_driver.cpp
Labels: bug, regression

#2944 Fix unneeded empty lines in 'TREE | MORE' display
  src/dos/program_more_output.cpp
Labels: bug

#2946 Ignore extensions when finding highest capture index
  src/capture/capture.cpp
Labels: plumbing

#2953 Add short prompts for MORE commands for 40 column screen modes
  src/dos/program_more.cpp
  src/dos/program_more_output.cpp
Labels: enhancement

#2954 Simplify translation workflow
  contrib/resources/translations/.gitattributes
  contrib/resources/translations/.gitignore
  contrib/resources/translations/README.md
  contrib/resources/translations/encode.bat
  contrib/resources/translations/encode.sh
  contrib/resources/translations/fr-traduction-lisez-moi.txt
  contrib/resources/translations/normalize.bat
  contrib/resources/translations/normalize.sh
  contrib/resources/translations/tools/readme.txt
  contrib/resources/translations/update-sources.sh
  contrib/resources/translations/utf-8/de.txt
  contrib/resources/translations/utf-8/en.txt
  contrib/resources/translations/utf-8/es.txt
  contrib/resources/translations/utf-8/fr.txt
  contrib/resources/translations/utf-8/it.txt
  contrib/resources/translations/utf-8/nl.txt
  contrib/resources/translations/utf-8/pl.txt
  contrib/resources/translations/utf-8/ru.txt
  scripts/verify-markdown.sh
Labels: translation

#2951 Implement DOS file/directory attributes support
  include/cross.h
  include/dos_system.h
  include/drives.h
  include/fs_utils.h
  include/string_utils.h
  src/dos/drive_fat.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/misc/cross.cpp
  src/misc/fs_utils.cpp
  src/misc/fs_utils_posix.cpp
  src/misc/fs_utils_win32.cpp
  src/misc/string_utils.cpp
Labels: enhancement

#2960 Remove the SSE 4.2 instruction set from the hardware requirements (`80.x` release branch PR)
  website/docs/downloads/linux.md
  website/docs/downloads/macos.md
  website/docs/downloads/windows.md
Labels: documentation, website

#2963 website: Remove Snap link from linux.md (main-branch PR)
  website/docs/downloads/linux.md
Labels: documentation, website

#2964 website: Remove Snap link from linux.md (80.x release-branch PR)
  website/docs/downloads/linux.md
Labels: documentation, website

#2968 Fixing missing header file for select() syscall when building on MacO…
  src/libs/manymouse/x11_xinput2.c
Labels: build system
