Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-08, with the labels that each got.

#2711 Link mt32emu statically in the MSYS2 CI release
  .github/workflows/windows-msys2.yml
Labels: Windows, CI

#2712 Change VESA BIOS branding to 'DOSBox Staging'
  src/config.h.in
  src/ints/int10_vesa.cpp
  src/platform/visualc/config.h
Labels: cleanup

#2713 Fix deactivation of queued joystick axis movement
  src/gui/sdl_mapper.cpp
Labels: SDL2

#2716 Always let MacOS homebrew overwrite conflicting junk files
  .github/workflows/macos.yml
Labels: macOS, CI

#2721 Check and log *nix `ioctl` return-code errors
  src/hardware/serialport/libserial.cpp
Labels: cleanup

#2723 String fixes in CONFIG command
  src/misc/programs.cpp
Labels: translation

#2722 Turn down loguru verbosity when started with following arugments
  src/gui/sdlmain.cpp
Labels: enhancement

#2728 Remove scan and pixel doubling config settings
  src/dosbox.cpp
  src/gui/render.cpp
Labels: enhancement, video

#2731 Fixes and cleanup of PCI BIOS
  include/inout.h
  src/hardware/pci_bus.cpp
  src/ints/bios.cpp
  src/ints/bios_pci.cpp
  src/ints/meson.build
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: bug, cleanup, voodoo

#2732 Update Linux AppData description
  contrib/linux/dosbox-staging.metainfo.xml
Labels: packaging

#2736 Fix altered shader pragmas not taking an effect when reloading the shader
  src/gui/render.cpp
Labels: bug, video

#2737 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2740 Fix const issue writing a png with png12
  src/capture/image/png_writer.cpp
Labels: cleanup

#2744 Fix invalid default config value for voodoo_memsize
  src/dosbox.cpp
Labels: bug

#2749 Window sizing improvements & aspect ratio related cleanup
  src/gui/sdlmain.cpp
Labels: enhancement, cleanup

#2760 Improve compile commits script
  scripts/compile_commits.sh
Labels: build system

#2773 Add missing mutex lock to RWQueue
  src/misc/rwqueue.cpp
Labels: bug

#2775 Notify all when RWQueue stops
  src/misc/rwqueue.cpp
Labels: plumbing

#2786 Update Catmull-Rom shader
  contrib/resources/glshaders/interpolation/catmull-rom.glsl
  src/gui/sdlmain.cpp
Labels: shaders

#2792 Revert increaseticks sleep to 1ms
  src/dosbox.cpp
Labels: plumbing

#2796 docs: Mention HiDPI support for Linux on front page
  website/overrides/home.html
Labels: website

#2799 Fix alignment of file size column in the DIR command's output
  src/shell/shell_cmds.cpp
Labels: bug

#2802 Track previously added userdata when deleting the SDL resize watch
  src/gui/sdlmain.cpp
Labels: bug, SDL2

#2805 Update packages/*.txt files to include ffmpeg and conan
  packages/NixOS.txt
  packages/debian-10-docker-apt.txt
  packages/debian-11-docker-apt.txt
  packages/fedora-latest.txt
  packages/freebsd.txt
  packages/macos-12-brew.txt
  packages/macos-latest-brew.txt
  packages/openbsd.txt
  packages/ubuntu-16.04-apt.txt
  packages/ubuntu-18.04-apt.txt
  packages/ubuntu-20.04-apt.txt
  packages/ubuntu-22.04-apt.txt
  packages/vcpkg.txt
  packages/windows-latest-msys2.txt
  packages/windows-msys2-clang-i686.txt
  packages/windows-msys2-clang-x86_64.txt
  packages/windows-msys2-gcc-i686.txt
  packages/windows-msys2-gcc-x86_64.txt
Labels: CI

#2806 Fix the calculation of vga.draw.lines_scaled when double scanning
  src/hardware/vga_draw.cpp
Labels: regression, video
