Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-04, with the labels that each got.

#2373 Enable vsync by default
  src/gui/sdlmain.cpp
Labels: enhancement

#2380 Drop volatile members in IMFC and reSIDfp
  src/hardware/imfc.cpp
  src/libs/residfp/array.h
Labels: cleanup

#2384 Fix batch file 'goto' for previous labels
  src/shell/shell_batch.cpp
Labels: bug

#2377 Add multi-monitor awareness mode for mouse capture
  include/mouse.h
  src/gui/sdlmain.cpp
  src/hardware/input/mouse.cpp
  src/hardware/input/mouse_config.cpp
  src/hardware/input/mouse_config.h
Labels: enhancement

#2381 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#2379 Present VFR duplicate frames on a tempo
  include/sdlmain.h
  src/gui/sdlmain.cpp
Labels: bug, video

#2385 Update Italian (it-IT) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2392 Gracefully quit stdin loops on program termination
  src/dos/dos.cpp
Labels: regression

#2393 Add crt/aperture.mono shader variant
  contrib/resources/glshaders/crt/aperture.mono.glsl
Labels: enhancement

#2419 Update Italian (it-IT) translation (improved some strings)
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2434 Make triangle_worker members threadsafe
  src/hardware/voodoo.cpp
Labels: cleanup, voodoo

#2436 docs: Show Mastodon link
  website/overrides/partials/footer.html
Labels: website

#2441 Fix regression in VGA draw's wrapped line case
  src/hardware/vga_draw.cpp
Labels: bug, video
