Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-10, with the labels that each got.

#2971 Fix file creation regression on case sensitive file systems
  include/dos_system.h
  src/dos/drive_cache.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/shell/shell_cmds.cpp
Labels: regression

#2974 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
Labels: translation

#2980 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
Labels: translation

#2986 Zero initalize memory allocation in GrowWriteMask in dyn_cache
  src/cpu/dyn_cache.h
Labels: regression

#2989 Fix for DOS error code being wrongly set on creating files
  src/dos/drive_local.cpp
Labels: bug, regression

#2995 Do not assert if mapperfile parameter is empty
  src/gui/sdl_mapper.cpp
Labels: bug

#2994 De-unionise X86PageEntry
  include/paging.h
  src/cpu/paging.cpp
  src/debug/debug.cpp
Labels: cleanup

#3001 Fix coverity sign extension warning
  src/hardware/vga_draw.cpp
Labels: plumbing

#3002 Fix incorrect version reporting in Virtualbox LOG_WARNING.
  src/hardware/virtualbox.cpp
Labels: bug

#3003 Use safe_strcpy and safe_strcat
  src/shell/shell_cmds.cpp
Labels: plumbing

#3005 Try again to fix Coverity warning in SDL Sound
  src/libs/decoders/SDL_sound.c
Labels: plumbing

#3006 Re-add the SDL Sound assert (third time's a charm?)
  src/libs/decoders/SDL_sound.c
Labels: plumbing

#3012 Sync enet with upstream version 2.3.6
  src/libs/enet/LICENSE
  src/libs/enet/include/enet.h
Labels: upstream sync

#3017 Sync whereami with upstream
  src/libs/whereami/whereami.c
Labels: upstream sync

#3004 Limit consecutive duplicate frames in VFR presentation mode
  include/sdlmain.h
  src/gui/sdlmain.cpp
Labels: bug

#3013 Remove fontstash library
  LICENSE
  src/libs/fontstash/fontstash.h
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: upstream sync

#3022 Update Tracy to 0.10
  meson.build
  subprojects/tracy.wrap
Labels: enhancement, external

#3020 Change drive macros to return boolean values
  include/drives.h
Labels: regression

#3028 Fix extended ASCII codes not being rendered in batch files
  include/shell.h
  src/shell/file_reader.cpp
  src/shell/file_reader.h
  src/shell/shell_batch.cpp
  tests/batch_file_tests.cpp
Labels: regression

#3031 Add batch file (Windows) to convert GOG cp437 config files to UTF-8
  contrib/scripts/GOGconf-cp437-to-UTF-8.bat
  contrib/scripts/GOGconf-cp437-to-UTF8.bat
Labels: enhancement, Windows

#3029 Add legacy codepage to UTF-8 script
  contrib/scripts/codepage_to_utf8.py
Labels: enhancement, macOS, Linux

#3033 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3038 Fix drive automounts
  include/shell.h
  src/shell/autoexec.cpp
  src/shell/shell.cpp
Labels: regression

#3042 Improve batch file to convert GOG cp437 config files to UTF-8
  contrib/scripts/GOGconf-cp437-to-UTF8.bat
  contrib/scripts/tools/readme-gog437.txt
  contrib/scripts/tools/readme-uconv.txt
Labels: enhancement, Windows

#3048 Tune the IBM Music Feature card's 0-dB level and default filter
  src/hardware/imfc.cpp
Labels: bug, audio

#3050 Harmonize ManyMouse support message in the build system
  meson.build
Labels: build system

#3034 Rework and improve `LS.COM` command
  contrib/resources/translations/it.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.lng
  include/shell.h
  src/dos/program_ls.cpp
  src/dos/program_ls.h
  src/dos/program_tree.cpp
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: enhancement, refactorization

#3066 Snip truism note from MIXER long help text
  src/dos/program_mixer.cpp
Labels: documentation, cleanup

#3067 Sync reSIDfp with upstream
  src/libs/residfp/WaveformGenerator.cpp
  src/libs/residfp/WaveformGenerator.h
Labels: upstream sync, audio

#3065 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
Labels: translation

#3069 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
Labels: translation

#3068 Fix the priority of the "set decibel volume" MIXER command
  src/dos/program_mixer.cpp
  tests/program_mixer_tests.cpp
Labels: bug

#3064 Handle host code pages when running `dosbox.exe --help` on Windows
  contrib/resources/mapping/MAIN.TXT
  include/string_utils.h
  src/gui/sdlmain.cpp
  src/misc/unicode.cpp
Labels: enhancement

#3071 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3072 Minor string fixes in 'MIXER' command
  src/dos/program_mixer.cpp
Labels: bug, translation

#3074 Fix duplicate SoundFont listing in mixer /listmidi
  src/midi/midi_fluidsynth.cpp
Labels: bug, midi
