Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-11, with the labels that each got.

#3079 Handle exiting when pause_when_inactive=true
  src/gui/sdlmain.cpp
Labels: bug

#3084 Add more definitions to Unicode engine
  contrib/resources/mapping-wikipedia.org/CP_20866.TXT
  contrib/resources/mapping-wikipedia.org/CP_28591.TXT
  contrib/resources/mapping-wikipedia.org/CP_28592.TXT
  contrib/resources/mapping-wikipedia.org/CP_28593.TXT
  contrib/resources/mapping-wikipedia.org/CP_28594.TXT
  contrib/resources/mapping-wikipedia.org/CP_28595.TXT
  contrib/resources/mapping-wikipedia.org/CP_28596.TXT
  contrib/resources/mapping-wikipedia.org/CP_28597.TXT
  contrib/resources/mapping-wikipedia.org/CP_28598.TXT
  contrib/resources/mapping-wikipedia.org/CP_28600.TXT
  contrib/resources/mapping-wikipedia.org/CP_28601.TXT
  contrib/resources/mapping-wikipedia.org/CP_28603.TXT
  contrib/resources/mapping-wikipedia.org/CP_28604.TXT
  contrib/resources/mapping-wikipedia.org/CP_28606.TXT
  contrib/resources/mapping-wikipedia.org/meson.build
  contrib/resources/mapping/ASCII.TXT
  contrib/resources/mapping/CAPITAL_SMALL.TXT
  contrib/resources/mapping/DECOMPOSITION.TXT
  contrib/resources/mapping/MAIN.TXT
  src/misc/unicode.cpp
Labels: enhancement

#3081 Set the icon on window regeneration
  src/gui/sdlmain.cpp
Labels: bug

#3085 Don't throttle emulation speed when window becomes unfocused
  include/cpu.h
  src/cpu/cpu.cpp
  src/dosbox.cpp
  src/gui/sdlmain.cpp
Labels: enhancement

#3092 Fix double-scanning & pixel-doubling handling in `openglnb` output mode
  src/gui/render.cpp
  src/gui/shader_manager.h
Labels: bug, shaders, video

#3098 Fix OpenGL symbol type mismatch warning at link time
  src/gui/sdlmain.cpp
Labels: build system, plumbing

#3099 Drop OpenGL PBO support
  include/sdlmain.h
  src/gui/sdlmain.cpp
Labels: plumbing, video

#3100 Only process MT-32 debug messages in debug builds
  src/midi/midi_mt32.cpp
Labels: bug, audio

#3105 Ignore speaker-output enable/disable commands on the SB16
  src/hardware/sblaster.cpp
Labels: regression, audio

#3117 Always write the default config if the primary config file is missing
  src/gui/sdlmain.cpp
Labels: bug

#3109 Workaround for keyboard problem in Ultima VIII: Pagan
  src/hardware/input/intel8042.cpp
  src/hardware/input/mouseif_ps2_bios.cpp
Labels: bug, regression

#3120 Fix register-level PS/2 mouse access when DOS mouse driver is disabled
  src/hardware/input/mouseif_ps2_bios.cpp
Labels: bug

#3121 Always log OpenGL shader and program info logs if they're non-empty
  src/gui/sdlmain.cpp
Labels: enhancement, shaders, video

#3130 Skip compiler if error instead of aborting in compile_commits.sh
  scripts/compile_commits.sh
Labels: enhancement

#3129 Release mouse if `config -set mouse_capture=nomouse` is executed
  src/hardware/input/mouse.cpp
Labels: bug

#3137 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
Labels: translation

#3141 Restore sane `max N%` cycles behaviour where 100% means 100%
  src/cpu/cpu.cpp
  src/dosbox.cpp
Labels: enhancement

#3139 Regenerate primary config file if it is empty
  include/control.h
  include/cross.h
  include/setup.h
  src/dos/dos_keyboard_layout.cpp
  src/gui/sdlmain.cpp
  src/misc/cross.cpp
  src/misc/messages.cpp
  src/misc/programs.cpp
  src/misc/setup.cpp
  tests/dosbox_test_fixture.h
Labels: enhancement

#3143 Normalise warnings messages
  src/capture/image/image_capturer.cpp
  src/capture/image/image_saver.cpp
  src/gui/render.cpp
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
  src/hardware/gameblaster.cpp
  src/hardware/gus.cpp
  src/hardware/imfc.cpp
  src/hardware/innovation.cpp
  src/hardware/joystick.cpp
  src/hardware/lpt_dac.cpp
  src/hardware/mixer.cpp
  src/hardware/ne2000.cpp
  src/hardware/pcspeaker.cpp
  src/hardware/pcspeaker_discrete.cpp
  src/hardware/pcspeaker_impulse.cpp
  src/hardware/ps1audio.cpp
  src/hardware/sblaster.cpp
  src/hardware/tandy_sound.cpp
  src/hardware/vga.cpp
  src/hardware/vga_crtc.cpp
  src/hardware/vga_gfx.cpp
  src/hardware/vga_misc.cpp
  src/hardware/vga_other.cpp
  src/hardware/vga_paradise.cpp
  src/hardware/vga_s3.cpp
  src/hardware/vga_seq.cpp
  src/hardware/vga_tseng.cpp
  src/hardware/vga_xga.cpp
Labels: enhancement

#3153 Minor Unicode definitions improvements
  contrib/resources/mapping/ASCII.TXT
  contrib/resources/mapping/MAIN.TXT
Labels: enhancement

#3149 Fix rounding when very close to an integer
  src/fpu/fpu_instructions.h
Labels: FPU emulation
