Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-02, with the labels that each got.

#2269 Improve caching of subpackages
  .github/workflows/analysis.yml
  .github/workflows/config.yml
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/pvs-studio.yml
  .github/workflows/windows-msys2.yml
  packages/macos-12-brew.txt
  packages/macos-latest-brew.txt
  scripts/extract-subprojects-tar.sh
  scripts/fetch-and-tar-subprojects.sh
Labels: CI

#2274 Improve verbosity of DELETE command
  src/shell/shell_cmds.cpp
Labels: bug

#2276 Update docs with supported versions of Windows, macOS, and Linux (#2258)
  docs/build-windows.md
  website/docs/about/index.md
  website/docs/downloads/development-builds.md
  website/docs/downloads/linux.md
  website/docs/downloads/macos.md
  website/docs/downloads/windows.md
Labels: documentation

#2277 Fix Sound Blaster DMA ADPCM frame count assertion error
  src/hardware/sblaster.cpp
Labels: regression

#2280 Don't block r/w file opens on r/o FAT images
  include/drives.h
  src/dos/drive_fat.cpp
Labels: regression

#2286 Don't restrict text video modes to the VFR presentation mode
  src/gui/sdlmain.cpp
Labels: bug

#2290 Move `bit_view` value assignment to a general function
  include/bit_view.h
  tests/bit_view_tests.cpp
Labels: plumbing

#2292 Drop Ubuntu 18.04 from the CI workflows
  .github/workflows/linux.yml
  .github/workflows/platforms.yml
Labels: CI

#2293 Improve i8042 emulation, fix KEYB.COM
  src/hardware/input/intel8042.cpp
Labels: bug

#2297 Import FPU scale fix for x86 normal core
  src/fpu/fpu_instructions_x86.h
Labels: FPU emulation

#2296 Use C++11 `std::nearbyint()` for nearest FPU round
  src/fpu/fpu_instructions.h
Labels: FPU emulation

#2298 Implement i8042 diagnostic dump
  src/hardware/input/intel8042.cpp
Labels: enhancement

#2300 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#2299 Fix mistake in a comment
  src/hardware/input/intel8042.cpp
Labels: bug

#2302 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2303 Add translation batch file for Windows
  contrib/resources/translations/.gitignore
  contrib/resources/translations/encode.bat
  contrib/resources/translations/tools/readme.txt
Labels: translation

#2301 Enable large disk image support
  include/bios_disk.h
  include/cross.h
  include/support.h
  src/dos/drive_fat.cpp
  src/dos/program_imgmount.cpp
  src/ints/bios_disk.cpp
  src/misc/support.cpp
Labels: enhancement

#2307 Suppress excessively verbose `sprintf` warnings on macos + clang
  .github/workflows/macos.yml
  meson.build
Labels: buildsystem
