Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-06, with the labels that each got.

#2564 Never hard-exit DOSBox when an x87 FPU stack overflow is detected
  include/fpu.h
Labels: FPU emulation

#2566 Add warning log if message is missing
  src/misc/messages.cpp
Labels: plumbing

#2545 Replace busy-wait atomic bool goto logic
  src/hardware/voodoo.cpp
Labels: enhancement, voodoo

#2569 Fix VESA 256 / 8-bit in Windows 3.1
  src/hardware/vga_draw.cpp
Labels: regression, video

#2570 Fix incorrect pixel aspect ratio calculation for all text modes
  src/hardware/vga_draw.cpp
Labels: video

#2568 De-SDL voodoo threading
  include/semaphore.h
  src/hardware/voodoo.cpp
  tests/meson.build
  tests/semaphore_tests.cpp
Labels: cleanup, voodoo

#2576 Fix a GUS regression when interpolating 16-bit samples
  src/hardware/gus.cpp
Labels: regression

#2578 Improve some config setting descriptions
  src/dosbox.cpp
Labels: documentation, cleanup

#2582 Include low width resolution in VGA scanning citeria
  src/hardware/vga_draw.cpp
Labels: regression, video

#2584 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2588 Auto-disable the integer scaling feature if the image is smaller than…
  src/dosbox.cpp
  src/gui/sdlmain.cpp
Labels: bug, video

#2596 Use int64_t consistently for tick durations
  include/timer.h
  src/cpu/cpu.cpp
  src/dos/drive_overlay.cpp
  src/dosbox.cpp
  src/gui/sdlmain.cpp
  src/hardware/ipx.cpp
  src/midi/midi.cpp
  src/misc/pacer.cpp
Labels: bug

#2608 Reset DOS mouse driver position granularity on every mode change
  src/hardware/input/mouseif_dos_driver.cpp
Labels: bug, regression

#2613 Sync GHC std::filesystem with v1.5.14
  src/libs/ghc/ghc/filesystem.hpp
Labels: upstream_sync

#2614 Refill the SB audio channel when DMA reaches terminal count (#233)
  src/hardware/sblaster.cpp
Labels: regression, audio

#2611 Fix mouse centering on high DPI displays with scaling enabled
  src/gui/sdlmain.cpp
Labels: bug

#2609 Cleanup AUTOEXEC.BAT generation
  include/keyboard.h
  src/hardware/input/keyboard.cpp
  src/shell/autoexec.cpp
Labels: bug

#2625 Restore authentic text mode pixel aspect ratio calculation
  src/hardware/vga_draw.cpp
Labels: regression, video

#2624 Don't emulate CDROM lag for stationary calls
  src/dos/cdrom.cpp
  src/dos/cdrom_image.cpp
Labels: regression

#2621 Unicode mapping for CYRILLIC LETTER I WITH GRAVE, RUBLE, BG
  contrib/resources/mapping/ASCII.TXT
  contrib/resources/mapping/CAPITAL_SMALL.TXT
  contrib/resources/mapping/DECOMPOSITION.TXT
  contrib/resources/mapping/MAIN.TXT
Labels: translation

#2626 Fix mounting directory with space in its name, passed as an argument
  src/shell/autoexec.cpp
Labels: bug, regression

#2630 Don't save command history to current working directory
  src/shell/shell.cpp
Labels: bug

#2633 Cleanup a Coverity null-deference reloading the shader
  src/gui/render.cpp
Labels: cleanup

#2634 Minor configuration file cleanups
  src/dosbox.cpp
Labels: cleanup

#2641 Fix problem with loading Unicode data files in some situations
  src/misc/unicode.cpp
Labels: bug

#2640 Rename command_history to shell_history, for consistency
  include/shell.h
  src/dosbox.cpp
  src/shell/shell.cpp
Labels: cleanup

#2638 Implemented VOL shell command
  include/shell.h
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: enhancement

#2643 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2645 Fix UTF8 to DOS conversion by mistake applied twice in autoexec code
  src/shell/autoexec.cpp
Labels: bug

#2648 Fix mouse movement limitation regression in some games
  src/hardware/input/mouseif_dos_driver.cpp
Labels: bug, regression

#2650 Show backtraces in debug builds using Loguru's assert
  src/config.h.in
  src/platform/visualc/config.h
Labels: plumbing

#2652 Enable loguru stack traces
  src/config.h.in
  src/libs/loguru/meson.build
  src/platform/visualc/config.h
Labels: enhancement

#2653 Fix bug where DTA can be modified by DELETE command
  src/shell/shell_cmds.cpp
Labels: bug
