Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-03, with the labels that each got.

#2309 Refactor WriteOut functions in program.cpp
  src/misc/programs.cpp
Labels: refactorization

#2314 Support the right control key on MacOS.
  src/gui/sdl_mapper.cpp
Labels: macOS

#2317 Contribute an SDL audio test tool
  contrib/sdl_test_audio/.gitignore
  contrib/sdl_test_audio/README.md
  contrib/sdl_test_audio/meson.build
  contrib/sdl_test_audio/src/main.cpp
Labels: SDL2

#2327 Update Italian (it-IT) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2329 Fix compilation error on `misc_util.h`
  src/hardware/serialport/misc_util.h
Labels: cleanup, SDL2

#2334 Increase max memory size to 3072 MB, minor cleanup
  include/mem.h
  src/dosbox.cpp
  src/hardware/memory.cpp
Labels: enhancement, cleanup

#2337 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#2326 Add Instructions to Build on Nix
  BUILD.md
  README.md
  docs/build-nix.md
  packages/NixOS.txt
Labels: documentation

#2333 Fix mouse problem with windowed mode and viewport_resolution setting
  src/hardware/input/mouse.cpp
Labels: bug, regression

#2349 Differentiate CLI arguments from markup tags with escapes
  contrib/resources/translations/de.lng
  contrib/resources/translations/en.lng
  contrib/resources/translations/es.lng
  contrib/resources/translations/it.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/ru.lng
  contrib/resources/translations/utf-8/de.txt
  contrib/resources/translations/utf-8/en.txt
  contrib/resources/translations/utf-8/es.txt
  contrib/resources/translations/utf-8/it.txt
  contrib/resources/translations/utf-8/nl.txt
  contrib/resources/translations/utf-8/pl.txt
  contrib/resources/translations/utf-8/ru.txt
  src/shell/shell.cpp
Labels: cleanup

#2358 Make the DOS module depend on SDL2 net
  src/dos/meson.build
Labels: SDL2, buildsystem

#2355 Normalise Windows context menus created by the installer
  contrib/windows_installer/DOSBox-Staging-setup.iss
Labels: Windows, buildsystem

#2360 Revise the README template & include link to the new Getting Started …
  docs/README.template
Labels: documentation

#2365 core_dyn_x86: Initialise rettype to avoid compiler warning
  src/cpu/core_dyn_x86/risc_x64.h
Labels: cleanup

#2372 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
  contrib/resources/translations/utf-8/nl.txt
Labels: translation
