Repository dosbox-staging/dosbox-staging, pull requests merged in 2023-05, with the labels that each got.

#2443 Add new glshader/misc dir to the Meson build
  contrib/resources/glshaders/meson.build
Labels: bug, shaders

#2454 docs (main): Fix SHA256 checksum reported for macOS package
  website/docs/downloads/macos.md
Labels: website

#2453 docs (80.x): Fix SHA256 checksum reported for macOS package
  website/docs/downloads/macos.md
Labels: website

#2446 Ignore trailing colon in shell redirection (#2240)
  src/shell/shell.cpp
  tests/shell_redirection_tests.cpp
Labels: regression

#2458 Improve Arabic support in Unicode engine
  contrib/resources/mapping/ASCII.TXT
  contrib/resources/mapping/MAIN.TXT
  src/misc/unicode.cpp
Labels: bug

#2473 Add package download URL to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: CI

#2477 Disable framebuffer acceleration for debugger
  src/libs/PDCurses/sdl2_queue/pdcscrn.cpp
Labels: bug, video

#2476 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2471 Replace invalid vector.end dereference with raw pointer access
  src/dos/drive_virtual.cpp
Labels: bug

#2490 Fix some mistakes in code page character to Unicode mappings
  contrib/resources/mapping-freedos.org/CP_30000.TXT
  contrib/resources/mapping-wikipedia.org/CP_853.TXT
  contrib/resources/mapping/MAIN.TXT
Labels: bug

#2489 Drop Visual Studio 2019-specific accomodations in `.clang-format`
  .clang-format
Labels: plumbing

#2491 Fix regression in palettized VGA line draw function
  src/hardware/vga_draw.cpp
Labels: regression

#2492 Skip hidden dot files when wildcard pattern is first
  src/misc/cross.cpp
Labels: enhancement, macOS

#2495 Fix macOS debugger crash
  src/libs/PDCurses/sdl2_queue/pdcscrn.cpp
Labels: bug

#2497 Update Italian (it-it) translation
  contrib/resources/translations/it.lng
  contrib/resources/translations/utf-8/it.txt
Labels: translation

#2498 Fix the scan code sequence for the `pause` key
  src/hardware/input/keyboard_scancodes.cpp
Labels: bug

#2500 Recommend the project-release tarball first (`main` website)
  website/docs/downloads/linux.md
Labels: packaging, website

#2501 Recommend the project-release tarball first (release website)
  website/docs/downloads/linux.md
Labels: packaging, website

#2508 Implement DOS mouse driver function 0x32
  src/hardware/input/mouseif_dos_driver.cpp
Labels: enhancement

#2516 Create and update joy binds even when physical joysticks aren't present
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
Labels: regression

#2493 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
  contrib/resources/translations/utf-8/pl.txt
Labels: translation

#2524 FCB argument regression fix
  src/shell/shell_misc.cpp
Labels: regression

#2529 Prefer evdev mouse API over xinput on Linux
  src/libs/manymouse/manymouse.c
Labels: Linux

#2528 Resize VGA within half the current frame-time (#2510)
  include/vga.h
  src/hardware/vga.cpp
  src/hardware/vga_crtc.cpp
Labels: regression, video

#2522 Make the RWQueue more usable for complex types
  include/rwqueue.h
  src/midi/midi_fluidsynth.cpp
  src/midi/midi_fluidsynth.h
  src/midi/midi_mt32.cpp
  src/midi/midi_mt32.h
  src/misc/rwqueue.cpp
  tests/rwqueue_tests.cpp
Labels: plumbing

#2531 Fix completion index assertion error
  src/shell/shell_misc.cpp
Labels: regression

#2535 Perform safe left-shift of signed values in dynrec operators
  src/cpu/core_dynrec/operators.h
Labels: cleanup

#2538 Fix problem with some software (like MSD.EXE) displaying garbage mouse driver info
  include/math_utils.h
  src/hardware/input/mouseif_dos_driver.cpp
Labels: bug

#2542 Copy only the available command line chars
  include/dos_inc.h
  src/shell/shell_misc.cpp
Labels: bug

#2561 Avoid checked-STL false positives in Coverity build
  .github/workflows/coverity.yml
Labels: CI

#2560 Fix the formatting of some config descriptions
  src/dosbox.cpp
Labels: cleanup
