Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-02, with the labels that each got.

#3370 Remove 500 ms delay when entering pause mode
  src/gui/sdlmain.cpp
Labels: enhancement

#3374 Fix invalid iterator crash in debug build
  src/ints/int10.cpp
  src/ints/int10_modes.cpp
Labels: regression, backport

#3378 Fix Maximum Scan Line CRTC register behaviour
  src/hardware/vga_crtc.cpp
Labels: regression, backport, video

#3382 Update broken vcpkg schema link
  vcpkg.json
Labels: Windows, build system

#3386 Fix crash on startup when `machine` is set to `hercules`
  src/hardware/vga_dac.cpp
Labels: regression, video

#3389 Create basic macOS notarization script
  contrib/macos/Entitlements.plist
  scripts/notarize-macos-dmg.sh
Labels: macOS, build system

#3384 Use GitHub runners for macOS builds
  .github/workflows/macos.yml
  packages/macos-12-brew.txt
  packages/macos-latest-brew.txt
Labels: macOS, build system

#3403 Fix IPX config help comment
  src/dosbox.cpp
Labels: bug, backport

#3397 Fix variables optimizing away when debugging MSClang builds
  src/libs/zmbv/zmbv.vcxproj
  tests/vs/tests.vcxproj
  vs/dosbox.vcxproj
Labels: Windows, build system

#3408 Clean up macOS notarization script
  scripts/notarize-macos-dmg.sh
Labels: macOS, build system

#3406 Fix sed creating backup files ending with "-e" in macOS bundle
  scripts/create-package.sh
Labels: macOS, build system

#3317 New Spanish translation
  contrib/resources/translations/es.lng
Labels: backport, translation

#3284 Use C++ system headers
  src/cpu/callback.cpp
  src/cpu/core_dyn_x86.cpp
  src/cpu/core_dyn_x86/dyn_fpu.h
  src/cpu/core_dynrec.cpp
  src/cpu/core_prefetch.cpp
  src/cpu/cpu.cpp
  src/debug/debug.cpp
  src/debug/debug_disasm.cpp
  src/debug/debug_gui.cpp
  src/debug/debug_win32.cpp
  src/dos/cdrom_ioctl_linux.cpp
  src/dos/dos_devices.cpp
  src/dos/dos_execute.cpp
  src/dos/dos_files.cpp
  src/dos/dos_ioctl.cpp
  src/dos/drive_fat.cpp
  src/dos/drive_local.cpp
  src/dos/drive_overlay.cpp
  src/dos/drive_virtual.cpp
  src/dos/program_biostest.cpp
  src/dos/program_boot.cpp
  src/dos/program_loadrom.cpp
  src/gui/render_scalers.cpp
  src/hardware/dma.cpp
  src/hardware/ipxserver.cpp
  src/hardware/joystick.cpp
  src/hardware/memory.cpp
  src/hardware/mpu401.cpp
  src/hardware/ps1audio.cpp
  src/hardware/serialport/libserial.cpp
  src/hardware/serialport/misc_util.h
  src/hardware/serialport/serialport.cpp
  src/hardware/serialport/softmodem.cpp
  src/hardware/vga_memory.cpp
  src/hardware/vga_misc.cpp
  src/hardware/vga_xga.cpp
  src/ints/bios.cpp
  src/ints/int10_vesa.cpp
  src/ints/xms.cpp
  src/misc/cross.cpp
  src/shell/shell.cpp
Labels: cleanup

#3404 Fix handling multiple game controllers
  src/gui/sdl_mapper.cpp
Labels: bug, SDL, backport, input handling

#3409 Improve 'keyboardlayout' option description
  src/dosbox.cpp
Labels: documentation, backport

#3412 Cleanup some missed C++ header conversions
  include/bios_disk.h
  include/hardware.h
  include/sdlmain.h
Labels: cleanup

#3396 Show memory read breakpoint with BPLIST
  src/debug/debug.cpp
Labels: debugger

#3419 Bump Coverity build from Clang 14 to Clang 15
  .github/workflows/coverity.yml
Labels: build system

#3418 Fix IPX ping value display
  src/hardware/ipx.cpp
  src/hardware/ipxserver.cpp
Labels: cleanup

#3420 Set BIOS_Destroy not changeable at runtime
  src/ints/bios.cpp
Labels: regression, backport

#3432 Portuguese (Brazilian) Translation
  contrib/resources/translations/br.lng
Labels: translation, localisation

#3428 Fix double-scanning behavior for SVGA/VESA games
  src/hardware/vga_crtc.cpp
Labels: regression, backport, video

#3427 Improve the help text of the LOADFIX command (#3221)
  src/dos/program_loadfix.cpp
Labels: documentation

#3438 Fix incomplete integration of Brazilian translation
  contrib/resources/translations/meson.build
  contrib/resources/translations/update-sources.sh
  src/dosbox.cpp
Labels: bug, translation

#3440 Only raise window when it is newly created
  src/gui/sdlmain.cpp
Labels: SDL, regression, backport, video

#3442 Add IBM XDF floppy support
  src/ints/bios_disk.cpp
Labels: enhancement

#3422 Ignore meson.build in VS tests project
  tests/vs/tests.vcxproj
  tests/vs/tests.vcxproj.filters
Labels: cleanup

#3413 Use uncompressed CPI files instead of compressed CPX ones
  contrib/resources/freedos-cpi/EGA.CPI
  contrib/resources/freedos-cpi/EGA.CPX
  contrib/resources/freedos-cpi/EGA10.CPI
  contrib/resources/freedos-cpi/EGA10.CPX
  contrib/resources/freedos-cpi/EGA11.CPI
  contrib/resources/freedos-cpi/EGA11.CPX
  contrib/resources/freedos-cpi/EGA12.CPI
  contrib/resources/freedos-cpi/EGA12.CPX
  contrib/resources/freedos-cpi/EGA13.CPI
  contrib/resources/freedos-cpi/EGA13.CPX
  contrib/resources/freedos-cpi/EGA14.CPI
  contrib/resources/freedos-cpi/EGA14.CPX
  contrib/resources/freedos-cpi/EGA15.CPI
  contrib/resources/freedos-cpi/EGA15.CPX
  contrib/resources/freedos-cpi/EGA16.CPI
  contrib/resources/freedos-cpi/EGA16.CPX
  contrib/resources/freedos-cpi/EGA17.CPI
  contrib/resources/freedos-cpi/EGA17.CPX
  contrib/resources/freedos-cpi/EGA2.CPI
  contrib/resources/freedos-cpi/EGA2.CPX
  contrib/resources/freedos-cpi/EGA3.CPI
  contrib/resources/freedos-cpi/EGA3.CPX
  contrib/resources/freedos-cpi/EGA4.CPI
  contrib/resources/freedos-cpi/EGA4.CPX
  contrib/resources/freedos-cpi/EGA5.CPI
  contrib/resources/freedos-cpi/EGA5.CPX
  contrib/resources/freedos-cpi/EGA6.CPI
  contrib/resources/freedos-cpi/EGA6.CPX
  contrib/resources/freedos-cpi/EGA7.CPI
  contrib/resources/freedos-cpi/EGA7.CPX
  contrib/resources/freedos-cpi/EGA8.CPI
  contrib/resources/freedos-cpi/EGA8.CPX
  contrib/resources/freedos-cpi/EGA9.CPI
  contrib/resources/freedos-cpi/EGA9.CPX
  contrib/resources/freedos-cpi/meson.build
  src/dos/dos_locale.cpp
Labels: plumbing, localisation

#3444 Cleanup of using namespace
  src/debug/debug.cpp
  src/debug/debug_gui.cpp
  src/dos/cdrom_image.cpp
  src/dos/drive_overlay.cpp
  src/gui/sdl_mapper.cpp
  src/hardware/gameblaster.cpp
  src/hardware/gus.cpp
  src/hardware/imfc.cpp
  src/hardware/innovation.cpp
  src/hardware/input/intel8042.cpp
  src/hardware/input/intel8255.cpp
  src/hardware/input/keyboard.cpp
  src/hardware/input/mouseif_dos_driver.cpp
  src/hardware/input/mouseif_ps2_bios.cpp
  src/hardware/lpt_dac.cpp
  src/hardware/opl.cpp
  src/hardware/ps1audio.cpp
  src/hardware/ston1_dac.cpp
  src/hardware/tandy_sound.cpp
  src/hardware/vga_draw.cpp
  src/hardware/vga_other.cpp
  src/hardware/voodoo.cpp
  src/ints/int10_modes.cpp
  src/misc/setup.cpp
  src/misc/support.cpp
  tests/bitops_tests.cpp
Labels: cleanup

#3446 Improve VGA double scanning criteria
  src/hardware/vga_draw.cpp
Labels: enhancement, backport, video

#3423 Create .clang-tidy
  .clang-tidy
Labels: documentation, discussion

#3293 Remove GCC_LIKELY/GCC_UNLIKELY
  include/compiler.h
  src/cpu/core_dyn_x86.cpp
  src/cpu/core_dyn_x86/decoder.h
  src/cpu/core_dyn_x86/risc_x64.h
  src/cpu/core_dyn_x86/risc_x86.h
  src/cpu/core_dynrec.cpp
  src/cpu/core_dynrec/decoder.h
  src/cpu/core_dynrec/decoder_basic.h
  src/cpu/core_dynrec/decoder_opcodes.h
  src/cpu/core_dynrec/risc_armv4le-o3.h
  src/cpu/core_dynrec/risc_armv4le-thumb-iw.h
  src/cpu/core_dynrec/risc_armv4le-thumb-niw.h
  src/cpu/core_dynrec/risc_armv4le-thumb.h
  src/cpu/core_normal/prefix_none.h
  src/cpu/dyn_cache.h
  src/cpu/paging.cpp
  src/debug/debug.cpp
  src/dos/dos_memory.cpp
  src/dos/drive_cache.cpp
  src/dosbox.cpp
  src/fpu/fpu_instructions.h
  src/fpu/fpu_instructions_x86.h
  src/gui/render.cpp
  src/gui/sdl_mapper.cpp
  src/hardware/input/mouse_interfaces.cpp
  src/hardware/input/mouse_manymouse.cpp
  src/hardware/input/mouseif_virtual_machines.cpp
  src/hardware/iohandler.cpp
  src/hardware/opl.cpp
  src/hardware/pic.cpp
  src/hardware/timer.cpp
  src/hardware/vga_crtc.cpp
  src/hardware/vga_dac.cpp
  src/hardware/vga_draw.cpp
  src/hardware/vga_memory.cpp
  src/hardware/vga_xga.cpp
  src/hardware/voodoo.cpp
  src/ints/int10_char.cpp
  src/ints/int10_modes.cpp
  src/ints/int10_put_pixel.cpp
  src/misc/unicode.cpp
Labels: cleanup

#3457 Upgrade deprecated Node.js 16 GitHub actions to latest
  .github/workflows/analysis.yml
  .github/workflows/debian-docker-build.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/pvs-studio.yml
  .github/workflows/windows-msvc.yml
  .github/workflows/windows-msys2.yml
Labels: CI

#3458 Update br.lng
  contrib/resources/translations/br.lng
Labels: translation, localisation
