Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-03, with the labels that each got.

#3463 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: backport, translation

#3465 Replace use of `stat` in imgmount
  src/dos/program_imgmount.cpp
Labels: DOS

#3460 Make PCjr application memory contiguous
  include/dos_memory.h
  src/dos/dos_memory.cpp
  src/dosbox.cpp
  src/ints/bios.cpp
Labels: game compatibility, DOS

#3469 Update Portuguese (br) translation
  contrib/resources/translations/br.lng
Labels: translation

#3470 Throw error if user attempts to change an unchangeable setting
  include/setup.h
  src/misc/programs.cpp
  src/misc/setup.cpp
Labels: enhancement

#3474 Fix MSVC CI builds
  .github/workflows/windows-msvc.yml
Labels: build system

#3477 Upgrade Windows CI setup-msbuild GitHub action
  .github/workflows/windows-msvc.yml
Labels: build system

#3480 Fix vcredist version for MSVC CI runner
  .github/workflows/windows-msvc.yml
Labels: build system

#3483 Allow SDL wraps to be bypassed on macOS
  meson.build
Labels: build system

#3493 Allow the PVS-Studio workflow run in forked PRs
  .github/workflows/pvs-studio.yml
Labels: CI

#3485 Fix shell history creation regression
  src/shell/shell_history.cpp
Labels: regression, DOS

#3503 Use GitHub actions cache for vcpkg
  .github/workflows/windows-msvc.yml
Labels: build system

#3505 Fix macOS CI workflow
  .github/workflows/macos.yml
Labels: build system

#3507 Add `vga_render_per_scanline` option
  src/dosbox.cpp
  src/hardware/vga_draw.cpp
Labels: game compatibility, regression, backport, video

#3522 Update simde to 0.8.0
  src/libs/simde/x86/mmx.h
Labels: external, plumbing

#3516 Implement seeking in MSCDEX
  src/dos/dos_mscdex.cpp
Labels: enhancement, game compatibility, audio

#3249 Improve title bar and make it configurable
  contrib/resources/translations/de.lng
  contrib/resources/translations/en.lng
  contrib/resources/translations/it.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.lng
  contrib/resources/translations/ru.lng
  include/dos_inc.h
  include/sdlmain.h
  include/video.h
  src/capture/capture.cpp
  src/capture/capture_audio.cpp
  src/cpu/cpu.cpp
  src/dos/dos.cpp
  src/dos/dos_execute.cpp
  src/dos/dos_keyboard_layout.cpp
  src/dos/dos_locale.cpp
  src/dos/dos_locale.h
  src/dos/program_boot.cpp
  src/dos/program_setver.cpp
  src/dos/program_setver.h
  src/gui/meson.build
  src/gui/sdl_mapper.cpp
  src/gui/sdlmain.cpp
  src/gui/titlebar.cpp
  src/gui/titlebar.h
  src/hardware/input/mouse.cpp
  src/hardware/mixer.cpp
  src/misc/programs.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: enhancement

#3532 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: backport, translation

#3530 Update de.lng
  contrib/resources/translations/de.lng
Labels: translation

#3525 Check the validity of leading path when checking device name
  src/dos/dos_devices.cpp
Labels: regression, backport, DOS

#3546 Release drafter enhancements
  scripts/release-notes-drafter.py
Labels: build system

#3549 Fix the 'In Extremis' game intro getting stuck
  src/hardware/input/keyboard.cpp
Labels: game compatibility, regression, backport

#3553 Log OpenGL vsync state
  src/gui/sdlmain.cpp
Labels: cleanup, backport
