Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-05, with the labels that each got.

#3657 Allow loadfix to execute batch files
  src/dos/program_loadfix.cpp
Labels: enhancement, DOS

#3662 Upgrade SIMDE to 0.8.2
  src/libs/simde/x86/mmx.h
Labels: upstream sync

#3665 Allow running the `INTRO` built-in from subshells
  src/dos/program_intro.cpp
Labels: bug

#3664 Fix broken shell_history_file config option (std::weak_ptr version)
  include/shell.h
  src/dosbox.cpp
  src/shell/shell.cpp
  src/shell/shell_misc.cpp
Labels: regression, DOS

#3647 Deactivate IRQ if byte is read from i8042 chip
  src/hardware/input/intel8042.cpp
Labels: bug, regression, backport

#3667 `CONFIG` command enhancements
  src/misc/programs.cpp
Labels: enhancement

#3671 Fix hang on exit after pressing the pause key
  src/ints/bios_keyboard.cpp
Labels: bug, input handling

#3658 Clarify build instructions for low memory targets
  BUILD.md
Labels: documentation

#3690 Update dev website from `release/0.81.x`
  website/docs/releases/linux.md
  website/docs/releases/macos.md
  website/docs/releases/release-notes/0.81.0.md
  website/docs/releases/release-notes/0.81.1.md
  website/docs/releases/windows.md
  website/mkdocs.yml
  website/overrides/home.html
Labels: website

#3697 Remove Fedora Linux related build instructions
  contrib/fedora/RPMBUILD.md
  contrib/fedora/dosbox-staging.spec
Labels: documentation, website

#3696 Improve reset handler
  src/ints/bios.cpp
Labels: enhancement

#3708 Improve the `core` and `cputype` setting descriptions
  src/cpu/cpu.cpp
Labels: enhancement

#3714 Map 'Capture MIDI action' to Ctrl+Alt+F6 (Cmd+Opt+F6) by default
  src/capture/capture.cpp
Labels: enhancement, midi

#3716 Fix warning when using a high cycles value on a non-dynamic core
  src/cpu/cpu.cpp
Labels: regression
