Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-12, with the labels that each got.

#4095 Sync/update Visual Studio filters
  src/libs/zmbv/.gitignore
  tests/vs/.gitignore
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: Windows, build system

#4098 Fix debugger keypresses not being registered on Windows
  include/support.h
  src/debug/debug.cpp
Labels: Windows, regression, input handling, debugger

#4102 Remove mirror links from the Getting Started guide
  website/docs/getting-started/beneath-a-steel-sky.md
  website/docs/getting-started/next-steps.md
  website/docs/getting-started/passport-to-adventure.md
  website/docs/getting-started/setting-up-prince-of-persia.md
  website/docs/getting-started/star-wars-dark-forces.md
Labels: documentation

#4114 Fix double free in TCPClientSocket destructor
  src/hardware/serialport/misc_util.cpp
Labels: bug, regression, networking

#4115 Fix some warnings in Windows CDROM code as shown by MSYS2
  src/dos/cdrom_win32.cpp
Labels: Windows, plumbing

#4116 Consider keyboard layout list random on GNOME
  src/misc/host_locale_macos.cpp
  src/misc/host_locale_posix.cpp
  src/misc/host_locale_win32.cpp
Labels: bug, Linux, localisation

#4125 Update italian (it) translation
  contrib/resources/translations/it.lng
Labels: translation

#4127 Fix version typo on the website for legacy Windows 7 support
  website/docs/releases/windows.md
Labels: website

#4130 Review auto-detection priorities for Italian keyboard layouts
  src/dos/dos_locale_data.cpp
Labels: localisation

#4129 Revert "Ensure physical host buttons only perform one bound event"
  src/gui/sdl_mapper.cpp
Labels: regression, input handling

#4124 Immediately save user mapper changes to disk
  src/gui/sdl_mapper.cpp
Labels: enhancement, input handling

#4131 Increase bind name display length in the mapper to avoid truncation
  include/mapper.h
  src/gui/sdl_mapper.cpp
Labels: enhancement, input handling
