Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-01, with the labels that each got.

#3299 Fix DOS_DeviceHasName function to correctly check string lengths
  src/dos/dos_devices.cpp
Labels: bug, regression, backport

#3303 Don't sign extend 16-bit immediates to 32-bit in ppc dynrec, fixes
  src/cpu/core_dynrec/risc_ppc.h
Labels: bug, endianness, backport, plumbing

#3301 Improve Sound Blaster DSP write buffer status IO (02x0Ch) logic
  src/hardware/sblaster.cpp
Labels: bug, audio

#3315 Manage sdlmain's DOS video mode as an `<optional>`
  include/sdlmain.h
  src/gui/render.cpp
  src/gui/sdlmain.cpp
Labels: bug, backport, video

#3316 MIDI capture: close file on fseek error
  src/capture/capture_midi.cpp
Labels: cleanup, backport, midi

#3325 Bump PVS Studio version to 7.28.78353.377
  .github/workflows/pvs-studio.yml
Labels: CI, backport

#3321 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: backport, translation

#3330 Fix shader auto-switching
  src/gui/sdlmain.cpp
Labels: bug, shaders, video

#3339 Don't use SDL wraps as fallback
  meson.build
Labels: bug, build system

#3340 Update SDL2 wrap
  subprojects/sdl2.wrap
Labels: external, build system

#3341 Add script to repackage the Windows ZIP release package
  scripts/repackage-windows-zip.sh
Labels: packaging

#3344 Re-enable LTO on macOS x86_64 builds
  .github/workflows/macos.yml
Labels: regression, build system

#3349 On Windows, use CreateProcess instead of execvp for restart function
  src/gui/sdlmain.cpp
Labels: bug, Windows, backport

#3351 Fix console color after restart
  src/gui/sdlmain.cpp
Labels: Windows, regression, backport

#3347 Map default "Restart" hotkey to PrimaryMod + Option + Home
  src/gui/sdlmain.cpp
Labels: enhancement, backport

#3356 Fix video regression in Catacomb 3D
  src/hardware/vga_crtc.cpp
Labels: regression, video

#3363 Improve the arcade CRT shaders
  contrib/resources/glshaders/crt/arcade-1080p.glsl
  contrib/resources/glshaders/crt/arcade-1440p.glsl
  contrib/resources/glshaders/crt/arcade-4k.glsl
  contrib/resources/glshaders/crt/arcade-sharp-1080p.glsl
  contrib/resources/glshaders/crt/arcade-sharp-1440p.glsl
  contrib/resources/glshaders/crt/arcade-sharp-4k.glsl
Labels: shaders, video
