Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-09, with the labels that each got.

#3907 Comment out voodoo logging for local blending API call
  src/hardware/voodoo.cpp
Labels: cleanup, voodoo

#3908 Fix ZMBV CompareBlock function returning a negative value for 24/32bpp types
  src/libs/zmbv/zmbv.cpp
Labels: regression, video

#3915 Fix SoundBlaster DMA stuttering in The Rocketeer
  src/hardware/sblaster.cpp
Labels: regression, audio

#3923 Fix data race on mixer volume change
  src/hardware/mixer.cpp
Labels: plumbing, audio

#3924 Handle double-quotes in the shell similar to real MS-DOS
  src/shell/shell_cmds.cpp
  tests/shell_cmds_tests.cpp
Labels: bug, DOS

#3926 Provide application name to SDL
  src/gui/sdlmain.cpp
Labels: enhancement, Linux

#3928 Fix data race in the mapper when using `autotype`
  src/gui/sdl_mapper.cpp
  src/shell/shell_cmds.cpp
Labels: bug, refactoring, plumbing

#3929 Fix CI to create Debian package on `main` push
  .github/workflows/debian-package.yml
Labels: Linux, CI

#3930 Follow-up fix for Debian package on `main` push
  .github/workflows/debian-package.yml
Labels: bug, CI

#3931 Use std::atomic for CaptureState enum
  src/capture/capture.cpp
Labels: plumbing

#3933 Fix 'launchable' in the Flathub metainfo.xml file
  contrib/linux/org.dosbox-staging.dosbox-staging.metainfo.xml
Labels: bug, packaging, regression

#3935 Use an optimal number of threads in Voodoo
  src/dosbox.cpp
  src/hardware/voodoo.cpp
Labels: enhancement, voodoo

#3942 Fix byte calculation overflow using pages per MB
  src/hardware/memory.cpp
Labels: regression

#3944 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: translation

#3946 Fix Windows 98 S3 driver regression
  src/hardware/vga_s3.cpp
Labels: regression, video, Windows 3.x

#3960 Let GUS use its documented IRQ, DMA, and base addresses
  src/hardware/gus.cpp
Labels: enhancement, regression, audio
