Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-07, with the labels that each got.

#3801 Add DOS Files to shutdown step to avoid a crash when shutting down
  include/dos_inc.h
  src/dos/dos.cpp
  src/dos/dos_files.cpp
Labels: bug

#3804 Fix file open error in ISO Drive
  src/dos/drive_iso.cpp
Labels: regression

#3797 Unicode API refactoring
  include/string_utils.h
  include/unicode.h
  src/dos/dos_locale.cpp
  src/dos/program_tree.cpp
  src/gui/titlebar.cpp
  src/hardware/input/mouse_manymouse.cpp
  src/misc/messages.cpp
  src/misc/programs.cpp
  src/misc/unicode.cpp
  src/shell/autoexec.cpp
  src/shell/shell_history.cpp
  src/shell/shell_misc.cpp
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: cleanup, plumbing

#3809 Add Debian package build scripts and workflow
  .github/workflows/debian-package.yml
  .gitignore
  contrib/linux/debian/control
  contrib/linux/debian/copyright
  contrib/linux/debian/dosbox-staging.lintian-overrides
  contrib/linux/debian/rules
  contrib/linux/debian/source/format
  contrib/linux/debian/source/lintian-overrides
  packages/debian-11-development.txt
  scripts/build-debian-package.sh
Labels: Linux, CI, build system

#3813 Fix Ring Buffer PrevIndex() wrapping behavior for non power of 2 size
  include/ring_buffer.h
Labels: plumbing, audio

#3814 Fix MMX crash on moralhardcandy
  src/cpu/mmx.cpp
Labels: bug, CPU/FPU emulation, demoscene

#3816 Add bisecting notes to build documentation
  BUILD.md
Labels: documentation

#3824 Presentation mode, host rate & vsync cleanup
  include/sdlmain.h
  src/gui/sdlmain.cpp
Labels: cleanup, video

#3826 Change ppc64 to use correct `POWERPC` target
  src/cpu/meson.build
Labels: build system, non-x86

#3827 Add comment about PPC64 big-endian and running 32-bit BE code
  src/cpu/meson.build
Labels: documentation, non-x86

#3838 Improve redirection handling in the DOS shell
  include/shell.h
  src/shell/shell.cpp
  tests/shell_redirection_tests.cpp
Labels: refactoring, regression, DOS

#3837 Minor FPU cleanup
  include/fpu.h
  src/cpu/core_dynrec/dyn_fpu.h
  src/cpu/mmx.cpp
  src/fpu/fpu.cpp
  src/fpu/fpu_instructions.h
Labels: cleanup, CPU/FPU emulation

#3841 Fix regression in voodoo 16-bit memory write
  src/hardware/voodoo.cpp
Labels: regression, video, voodoo

#3840 Fix CD audio support on physical USB drives on Windows
  src/dos/cdrom_win32.cpp
Labels: bug, Windows, audio

#3844 Fix assert failure from incorrectly mapping result of SDL_GL_SwapInterval()
  src/gui/sdlmain.cpp
Labels: SDL, regression, video

#3847 Use inline memory routines for MMX
  src/cpu/core_dyn_x86/dyn_mmx.h
  src/cpu/core_dynrec/dyn_mmx.h
Labels: cleanup
