Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-06, with the labels that each got.

#3722 Set CMOS_Destroy not changeable at runtime
  src/hardware/cmos.cpp
Labels: bug, backport

#3718 Make parameter addresses properly sized in ppc64le dynrec (fixes #3686)
  src/cpu/core_dynrec/risc_ppc64le.h
Labels: bug, Linux, non-x86

#3725 Check if hardware cursor is actually being enabled or disabled before setting VGA_LineDraw
  src/hardware/vga_s3.cpp
Labels: bug, demoscene, regression, video

#3729 Various MT-32 improvements & fix Bumpy's Arcade Fantasy intro tune
  src/midi/midi_mt32.cpp
Labels: enhancement, game compatibility, audio, midi

#3732 Fix switch to dynamic core warning edge case
  src/cpu/cpu.cpp
Labels: bug

#3734 Minor `vga_draw.cpp` refactor
  src/hardware/vga_draw.cpp
Labels: refactoring, video

#3736 Remove hard-coded version string from MSVC CI
  .github/workflows/windows-msvc.yml
Labels: Windows, CI

#3746 Use CreateFileW on Windows to create file in local_drive_create_file()
  src/misc/fs_utils_win32.cpp
Labels: Windows, regression

#3747 Search for numbered clang-format binaries in format-commit.sh
  scripts/format-commit.sh
Labels: plumbing

#3751 Update italian (it) translation
  contrib/resources/translations/it.lng
Labels: translation

#3753 `CONFIG -h` should only list visible setting values
  src/gui/sdlmain.cpp
Labels: regression

#3755 Fix the GUS reset register's startup behavior
  src/hardware/gus.cpp
Labels: refactoring, regression, audio

#3766 Fix decrementing of MPU-401 track and conductor counters
  src/hardware/mpu401.cpp
Labels: regression, audio, midi

#3767 Use linear 128 KB video memory pages for VESA modes
  src/ints/int10_modes.cpp
Labels: enhancement, game compatibility, video, eXoDOS/Win3x

#3772 Initialise the OPL operators per the Adlib's v1.51 driver
  src/hardware/opl.cpp
Labels: enhancement, game compatibility, audio

#3779 Use wrapping behavior on localFile seek position
  src/dos/drive_local.cpp
Labels: regression, DOS, Windows 3.x

#3361 Basic CMake support
  CMakeLists.txt
  src/CMakeLists.txt
  src/capture/CMakeLists.txt
  src/config.h.in
  src/cpu/CMakeLists.txt
  src/debug/CMakeLists.txt
  src/dos/CMakeLists.txt
  src/fpu/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/hardware/CMakeLists.txt
  src/ints/CMakeLists.txt
  src/libs/CMakeLists.txt
  src/libs/ESFMu/CMakeLists.txt
  src/libs/PDCurses/CMakeLists.txt
  src/libs/YM7128B_emu/CMakeLists.txt
  src/libs/decoders/CMakeLists.txt
  src/libs/loguru/CMakeLists.txt
  src/libs/nuked/CMakeLists.txt
  src/libs/residfp/CMakeLists.txt
  src/libs/simde/CMakeLists.txt
  src/libs/tal-chorus/CMakeLists.txt
  src/libs/whereami/CMakeLists.txt
  src/libs/zmbv/CMakeLists.txt
  src/midi/CMakeLists.txt
  src/misc/CMakeLists.txt
  src/shell/CMakeLists.txt
  vcpkg.json
Labels: build system

#3790 Add warning about CMake support being experimental
  BUILD.md
  README.md
  docs/build-freebsd.md
  docs/build-haiku.md
  docs/build-macos.md
  docs/build-nix.md
  docs/build-openbsd.md
  docs/build-windows.md
Labels: documentation, build system

#3789 Do not hard exit when running `SET /P`
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: bug, enhancement, DOS

#3777 Replace botched Tyrian 2000 setup fix with a (hopefully) proper one
  src/hardware/input/intel8042.cpp
Labels: bug, regression, backport

#3784 Replace Ultima VIII keyboard hack with a proper solution
  src/cpu/callback.cpp
  src/hardware/input/intel8042.cpp
  src/ints/bios_keyboard.cpp
Labels: enhancement, cleanup
