Repository dosbox-staging/dosbox-staging, pull requests merged in 2024-04, with the labels that each got.

#3560 Update Italian (it) translation
  contrib/resources/translations/it.lng
Labels: backport, translation

#3572 Unify use of prop->Set_values
  include/setup.h
  src/dosbox.cpp
  src/gui/render.cpp
  src/gui/sdlmain.cpp
  src/hardware/gus.cpp
  src/hardware/imfc.cpp
  src/hardware/innovation.cpp
  src/hardware/input/mouse_config.cpp
  src/hardware/mixer.cpp
  src/hardware/vga_other.cpp
  src/midi/midi.cpp
  src/midi/midi_mt32.cpp
  src/misc/setup.cpp
  src/shell/shell.cpp
Labels: cleanup, refactoring

#3568 Restore double scanning support for VGA text modes
  src/hardware/vga_draw.cpp
Labels: regression, backport, video

#3578 Inherit batch file echo state from parent
  src/shell/shell_misc.cpp
Labels: regression, DOS

#3571 Fix 'output' and other 'sdl' settings not changeable in runtime
  src/gui/sdl_mapper.cpp
Labels: bug, regression

#3583 Do not auto-run DOSBox Staging after installing it on Windows
  contrib/windows_installer/DOSBox-Staging-setup.iss
Labels: Windows, packaging

#3587 Use SB* and OPL logging prefixes consistely in all scenarios
  src/hardware/sblaster.cpp
Labels: cleanup, backport, audio

#3598 Pin CMake version for MSVC runner
  .github/workflows/windows-msvc.yml
Labels: build system

#3597 Port video memory I/O delay tweak from DOSBox-X
  include/vga.h
  src/dosbox.cpp
  src/hardware/vga_memory.cpp
Labels: enhancement, game compatibility, backport, video

#3600 Update English (en) translation for 0.81.1
  contrib/resources/translations/en.lng
Labels: translation

#3606 Advance vcpkg baseline to upgrade to SDL 2.30.0
  vcpkg.json
Labels: upstream sync

#3611 Fix the width of VGA text modes being incorrectly set sometimes
  src/hardware/vga_draw.cpp
Labels: regression, backport, video

#3610 Avoid false positive warnings in translations
  src/misc/messages.cpp
Labels: bug, translation, localisation

#3617 Avoid unnecessary new-lines
  src/midi/midi.cpp
  src/misc/setup.cpp
Labels: regression

#3621 Do not treat illegal command line switches as commands
  src/shell/autoexec.cpp
Labels: bug, regression, backport

#3624 Update Spanish translation
  contrib/resources/translations/es.lng
Labels: translation

#3625 Remove -usecd and -listcd MOUNT parameters from INTRO and the README
  README
  src/dos/program_intro.cpp
Labels: documentation

#3630 Update German (de) translation
  contrib/resources/translations/de.lng
Labels: translation

#3633 Update Polish (pl) translation
  contrib/resources/translations/pl.lng
Labels: backport, translation

#3637 Fix not being able to select Game Blaster / CMS emulation
  src/hardware/sblaster.cpp
Labels: regression, audio
