Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-08, with the labels that each got.

#4459 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#4467 Show stack trace symbols in Loguru dump
  src/libs/loguru/CMakeLists.txt
Labels: build system

#4470 Fix Windows + Ninja compilation error
  src/gui/sdlmain.cpp
Labels: Windows

#4479 Cleanup the resources directory
  LICENSE
  extras/dos-programs/README.md
  extras/dos-programs/cpi-master.zip
  extras/dos-programs/cpidos-master.zip
  resources/freedos-cpi/APPINFO/CPIDOS-2.3.LSM
  resources/freedos-cpi/APPINFO/CPIDOS-3.0.LSM
  resources/freedos-cpi/DOC/CODEPAGE-ISO.TXT
  resources/freedos-cpi/DOC/CODEPAGE-KOI.TXT
  resources/freedos-cpi/DOC/CODEPAGE-MAC.TXT
  resources/freedos-cpi/DOC/CODEPAGE-WIN.TXT
  resources/freedos-cpi/DOC/CODEPAGE.TXT
  resources/freedos-cpi/DOC/HISTORY-ISO.TXT
  resources/freedos-cpi/DOC/HISTORY-KOI.TXT
  resources/freedos-cpi/DOC/HISTORY-MAC.TXT
  resources/freedos-cpi/DOC/HISTORY-WIN.TXT
  resources/freedos-cpi/DOC/HISTORY.TXT
  resources/freedos-cpi/DOC/README-ISO.TXT
  resources/freedos-cpi/DOC/README-KOI.TXT
  resources/freedos-cpi/DOC/README-MAC.TXT
  resources/freedos-cpi/DOC/README-WIN.TXT
  resources/freedos-cpi/DOC/README.TXT
  resources/freedos-cpi/LICENSE/LICENSE
  resources/freedos-keyboard/APPINFO/KEYB_LAY.LSM
  resources/freedos-keyboard/DOC/BE-INTL.TXT
  resources/freedos-keyboard/DOC/CHEROKEE.TXT
  resources/freedos-keyboard/DOC/ENHANCED.TXT
  resources/freedos-keyboard/DOC/FR-INTL.TXT
  resources/freedos-keyboard/DOC/GEORGIA.TXT
  resources/freedos-keyboard/DOC/HISTORY.TXT
  resources/freedos-keyboard/DOC/IT-INTL.TXT
  resources/freedos-keyboard/DOC/JP106.TXT
  resources/freedos-keyboard/DOC/LAYOUTS.TXT
  resources/freedos-keyboard/DOC/PO-INTL.TXT
  resources/freedos-keyboard/DOC/README.TXT
  resources/freedos-keyboard/DOC/RUSSIA.TXT
  resources/freedos-keyboard/DOC/SP-INTL.TXT
  resources/freedos-keyboard/DOC/UK-INTL.TXT
  resources/freedos-keyboard/DOC/US-INTL.TXT
  resources/freedos-keyboard/LICENSE/LICENSE
Labels: cleanup

#4487 CDROM Audio: Do not continue to the next track if less than 2 seconds remains
  src/dos/cdrom_image.cpp
Labels: bug, game compatibility, audio

#4488 Update italian (it) translation
  resources/translations/it.lng
Labels: translation
