Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-06, with the labels that each got.

#4356 DOS mouse driver minor fixes/cleanups
  src/hardware/input/mouseif_dos_driver.cpp
Labels: bug, cleanup, input handling

#4362 Cleanup AUTOEXEC.BAT regeneration
  include/autoexec.h
  src/dos/dos_code_page.cpp
  src/dos/dos_programs.cpp
  src/dos/drive_virtual.cpp
  src/shell/autoexec.cpp
Labels: cleanup

#4378 Update macOS build instructions
  docs/build-macos.md
Labels: documentation

#4382 Make Windows CI build errors visible
  .github/workflows/windows.yml
Labels: CI

#4386 Fix for translated '-list-countries' and similar messages
  src/dos/dos_locale.cpp
Labels: bug

#4376 Only register disk noise callback if required
  src/hardware/disk_noise.cpp
Labels: bug
