Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-07, with the labels that each got.

#4404 Remove KDevelop files
  .kdev4/dosbox-staging.main.kdev4
  dosbox-staging.main.kde4
Labels: plumbing

#4408 Add FROM_HASH option to the compile commits script
  scripts/tools/compile-commits.sh
Labels: enhancement, build system

#4412 Fixed reversed audio channels for SoundBlaster Pro
  src/hardware/sblaster.cpp
Labels: audio

#4421 Reintroduce vcpkg binary caching
  .github/actions/setup-vcpkg/action.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/pvs-studio.yml
  .github/workflows/windows.yml
Labels: CI

#4432 Move `plugins` dir to the root in the Linux & Windows packages
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: Windows, Linux, CI, packaging

#4400 Restore deprecated mixer channel name aliases
  include/channel_names.h
  src/dos/program_mixer.cpp
  src/hardware/mixer.cpp
Labels: regression, audio
