Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-03, with the labels that each got.

#4216 Revert "Keep GUS running (and rendering) on IO port reads"
  src/hardware/gus.cpp
Labels: regression, backport, audio

#4221 Display the correct real or protected mode cycles value in the title bar
  src/cpu/cpu.cpp
Labels: bug, regression, backport

#4219 Fix GUS resampling regression & emulate the GUS' output more authentically
  src/hardware/gus.cpp
  src/hardware/gus.h
Labels: enhancement, regression, backport, audio

#4223 Improve default crossfeed setting behaviour
  src/hardware/mixer.cpp
Labels: enhancement, backport, audio

#4226 Fix incorrect check cast in IMFC
  src/hardware/imfc.cpp
Labels: bug, audio

#4234 Replace infinity with max float in prop parser
  src/misc/setup.cpp
Labels: Windows, tests

#4235 Update italian (it) translation
  contrib/resources/translations/it.lng
Labels: localisation

#4236 Update Polish (pl) translation, for 0.82.1 release
  contrib/resources/translations/pl.lng
Labels: translation

#4228 Allow graceful failure if OpenGL context could not be created
  src/gui/sdlmain.cpp
Labels: bug, backport, video

#4252 Improve GUS config setting descriptions
  src/hardware/gus.cpp
Labels: documentation, audio

#4250 Enable bilinear filtering for the 3dfx Voodoo by default
  src/dosbox.cpp
  src/hardware/voodoo.cpp
  src/hardware/voodoo.h
  vs/dosbox.vcxproj
  vs/dosbox.vcxproj.filters
Labels: enhancement, video, voodoo

#4265 Update Dutch (nl) translation
  contrib/resources/translations/nl.lng
Labels: translation
