Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-05, with the labels that each got.

#4302 Fix edge case where CDROM mixer hangs at the end of a track
  src/dos/cdrom.h
  src/dos/cdrom_image.cpp
Labels: bug, game compatibility, regression, audio

#4308 Restore Debian 11 dependency file
  packages/debian-11-development.txt
Labels: Linux, CI

#4312 Update italian (it) translation
  contrib/resources/translations/it.lng
Labels: translation

#4319 Use personal access token for the release drafter
  .github/workflows/draft-release-notes.yml
Labels: CI

#4313 Use untranslated keyboard layout name for logging
  src/dos/dos_code_page.cpp
  src/dos/dos_keyboard_layout.cpp
  src/dos/dos_locale.cpp
  src/dos/dos_locale.h
Labels: bug, regression, localisation

#4288 Adapt the Linux app_id to the Flatpak requirements
  .github/workflows/linting.yml
  contrib/icons/Makefile
  contrib/icons/meson.build
  contrib/linux/install-icons.sh
  contrib/linux/meson.build
  contrib/linux/org.dosbox_staging.dosbox_staging.desktop
  contrib/linux/org.dosbox_staging.dosbox_staging.metainfo.xml
  include/dosbox.h
  scripts/create-package.sh
  scripts/update-copyright-date.sh
Labels: Linux, build system, backport

#4326 Change 'ux' keyboard layout autodetection priority to low
  src/dos/dos_locale_data.cpp
Labels: regression, localisation

#4327 Update contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#4339 Fix file timestamp conversion on Windows
  src/misc/fs_utils_win32.cpp
Labels: bug, DOS

#4345 Replace non-ASCII copyright symbol in winres.rc
  src/winres.rc
Labels: Windows, build system

#4349 Simplify 'for' help message handling
  contrib/resources/translations/br.lng
  contrib/resources/translations/de.lng
  contrib/resources/translations/es.lng
  contrib/resources/translations/it.lng
  contrib/resources/translations/nl.lng
  contrib/resources/translations/pl.lng
  include/messages.h
  src/misc/messages.cpp
  src/shell/shell.cpp
  src/shell/shell_cmds.cpp
Labels: cleanup, localisation

#4354 Fix reporting of failed CI builds on Linux and macOS
  .github/workflows/linux.yml
  .github/workflows/macos.yml
Labels: macOS, Linux, CI
