Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-02, with the labels that each got.

#4169 Fix SoundBlaster Notify Unlock
  src/hardware/mixer.cpp
Labels: regression, audio

#4170 Add macOS CMake + vcpkg release build workflow
  .github/workflows/macos-cmake.yml
  .github/workflows/macos.yml
  .gitignore
  BUILD.md
  CMakeLists.txt
  CMakePresets.json
  scripts/verify-macos-dylibs.py
  src/capture/CMakeLists.txt
  src/config.h.in.cmake
  src/dos/CMakeLists.txt
  src/dos/program_mount.cpp
  src/gui/CMakeLists.txt
  src/hardware/CMakeLists.txt
  src/midi/CMakeLists.txt
  vcpkg.json
Labels: macOS, CI, build system

#4171 Remove Coverity static analysis
  .github/workflows/coverity.md
  .github/workflows/coverity.yml
  CONTRIBUTING.md
  README.md
  scripts/fetch-workflows.sh
Labels: CI, build system

#4182 Fix `INT10_SetVideoMode()` regression
  src/ints/int10_modes.cpp
Labels: game compatibility, backport, video

#4175 Increase the number of audio frames generated by SoundBlaster when the mixer is underflowing
  src/hardware/sblaster.cpp
  src/hardware/sblaster.h
Labels: enhancement, regression, audio

#4183 Delete the GUS tick handler in the destructor
  src/hardware/gus.cpp
Labels: regression, backport, audio

#4184 Add Windows presets for CMake
  CMakePresets.json
  src/hardware/CMakeLists.txt
Labels: build system

#4191 Replace #if WIN32 with #ifdef WIN32
  src/dos/program_intro.cpp
  src/gui/sdlmain.cpp
Labels: Windows, build system

#4174 Clean up vertical bars fix FPU code
  include/fpu.h
  src/cpu/core_dynrec/dyn_fpu.h
  src/cpu/mmx.cpp
  src/fpu/fpu.cpp
  src/fpu/fpu_instructions.h
Labels: cleanup, CPU/FPU emulation, video

#4192 Remove s390x and ppc64le platform builds & simplify workflow
  .github/workflows/platforms.yml
Labels: CI, build system

#4188 Add bounds checking to SoundBlaster's read_dma_16bit() and read_dma_8bit()
  src/hardware/sblaster.cpp
Labels: regression, audio

#4195 Mute audio when the mapper is active
  src/gui/sdl_mapper.cpp
Labels: regression, backport, audio

#4202 Don't let the mixer request frames for SoundBlaster in fast-forward mode
  src/hardware/sblaster.cpp
Labels: regression, audio

#4187 Document Microsoft Digital Media Pro Keyboard scancodes
  include/keyboard.h
  src/hardware/input/README.md
  src/hardware/input/keyboard_scancodes.cpp
Labels: documentation, cleanup, input handling

#4186 Initial Linux support in CMake files
  BUILD.md
  CMakeLists.txt
  CMakePresets.json
  src/capture/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/hardware/CMakeLists.txt
  src/libs/decoders/CMakeLists.txt
  src/midi/CMakeLists.txt
Labels: Linux, build system

#4206 Improve some mouse setting descriptions
  src/dosbox.cpp
  src/hardware/input/mouse_config.cpp
Labels: documentation, enhancement, backport, input handling

#4209 Set CMAKE_EXPORT_COMPILE_COMMANDS by default
  CMakeLists.txt
Labels: build system
