Repository dosbox-staging/dosbox-staging, pull requests merged in 2025-09, with the labels that each got.

#4499 Remove max frame time check in frame presentation
  src/gui/sdlmain.cpp
Labels: bug, regression, video

#4482 Update mapper.cpp - correct comment about ABNT1
  src/gui/mapper.cpp
Labels: documentation

#4496 Correct EMS Set Handle Name to read from correct registers
  src/ints/ems.cpp
Labels: bug, DOS

#4510 Fix release package name generation on macOS
  scripts/ci/get-version.sh
Labels: macOS, CI
